.github/workflows/ci.yml
package.json
packages/test/package.json
packages/test/src/test-integration.ts
scripts/wait-on-temporal.js

Run integrations tests in CI

---

packages/test/src/test-workflows.ts
packages/workflow/src/internals.ts

Due to [updates](https://github.com/temporalio/sdk-core/pull/53) in sdk-core proto definitions.

Update activation job interfaces

---

packages/test/src/test-integration.ts
packages/worker/native/index.d.ts
packages/worker/native/src/lib.rs
packages/worker/src/worker.ts
packages/worker/tsconfig.json

What was changed:
Added the basic functionality of configuring the worker's server connection.
Closes issue: 
Closes #38 
Added a test that asserts the worker options are generated correctly

Add ServerOptions to worker interface

---

docs/logging.md
packages/create-project/samples/worker.ts
packages/meta/README.md
packages/test/src/mock-native-worker.ts
packages/test/src/run-a-worker.ts
packages/test/src/test-integration.ts
packages/test/src/test-worker-activities.ts
packages/test/src/test-worker-lifecycle.ts
packages/test/src/test-workflows.ts
packages/worker/README.md
packages/worker/native/Cargo.lock
packages/worker/native/Cargo.toml
packages/worker/native/index.d.ts
packages/worker/native/src/lib.rs
packages/worker/src/activity.ts
packages/worker/src/worker.ts
packages/workflow/src/internals.ts

Use the async core interface introduced in https://github.com/temporalio/sdk-core/pull/77
Worker is now created with the static async `Worker.create` method.
Ran the existing tests which needed some modifications.
Docs were updated.

Use async core interface

---

.github/workflows/ci.yml

This should be reverted as soon as the brew install issue for `mingw-w64` is fixed.

Temporarily disable Windows build in CI

---

packages/create-project/samples/worker.ts
packages/test/src/mock-native-worker.ts
packages/test/src/run-a-worker.ts
packages/test/src/test-integration.ts
packages/test/src/test-worker-activities.ts
packages/test/src/test-worker-lifecycle.ts
packages/test/src/test-worker.ts
packages/worker/src/worker.ts

Move __dirname Worker.create() param into WorkerOptions.
It simplifies using and explaining `WorkerOptions` by removing the need for `null`s in `workflowsPath` and `activitiesPath`.
None
Standard test suitte.
Updated the documentation and sample for the docs site.

Move __dirname Worker.create() param into WorkerOptions

---

packages/activity/src/index.ts
packages/test-activities/src/index.ts
packages/test-interfaces/src/index.ts
packages/test-workflows/src/cancel-http-request.ts
packages/test-workflows/src/resolvable-promise.ts
packages/test/src/mock-native-worker.ts
packages/test/src/test-integration.ts
packages/test/src/test-worker-activities.ts
packages/test/src/zeroes-http-server.ts
packages/worker/src/activity.ts
packages/worker/src/worker.ts

- Activity Info was missing
- Cancellation tests are less flakey with signals than with timeouts
-
Documented the Activity Info interface

Add Activity Info to context, test cancellation with signals

---

packages/activity/src/index.ts
packages/test/src/mock-native-worker.ts
packages/test/src/test-worker-activities.ts
packages/test/src/test-worker-error-handling.ts
packages/test/src/test-worker-lifecycle.ts
packages/worker/native/Cargo.lock
packages/worker/native/Cargo.toml
packages/worker/native/index.d.ts
packages/worker/native/src/errors.rs
packages/worker/native/src/lib.rs
packages/worker/scripts/build-rust.js
packages/worker/src/errors.ts
packages/worker/src/index.ts
packages/worker/src/worker.ts

- Heartbeat details is now an optional parameter
- Use typed errors for errors returned from Core
- Add error handling for errors returned from Core
- Add worker State types: `DRAINING | DRAINED`
- Fix isolates not being disposed on `removeFromCache` activations
- Always delete index.node before building rust code
1. Closes #51 
Added tests for the added error handling.
Only docstrings

Handle errors returned from core correctly

---

package-lock.json
package.json
packages/test/src/test-worker-error-handling.ts
packages/worker/package.json
packages/worker/src/tracing.ts
packages/worker/src/worker.ts
packages/worker/src/workflow.ts

- Add opentelemetry to the project
- Instrument WF activations
- Add `@opentelemetry/sdk-node` and `@opentelemetry/exporter-jaeger` as dev dependencies for now to be used in bench test
- Add `long@^4.0.0` dev dependency to ensure it is loaded from proto module after adding exporter-jaeger which depends on thriftrw which in turn depends on `long@^2.4.0`
- Fix auto WF cache evict on worker draining and idle
Prepare project for telemetry and profile slow WF activation processing.
Ran a bench test and manually verified trace output in jaeger UI
Not yet, this does not add official support.

Add opentelemetry to project and instrument WF activations

---

packages/test/src/bench.ts
packages/test/src/test-integration.ts
packages/test/src/test-worker-error-handling.ts
packages/worker/native/Cargo.lock
packages/worker/native/src/errors.rs
packages/worker/native/src/lib.rs
packages/worker/src/errors.ts
packages/worker/src/worker.ts
packages/worker/src/workflow.ts

- Created a bench test
- Update core
- Remove error handling for activity heartbeats
1. Closes issue:
Closes #79 
Ran `bench.js` locally.
We've been running this bench script for over a week and fixing issues with both the node and core SDKs.
Results showed that we had a memory leak from creating modules which was an [isolated-vm issue](https://github.com/laverdet/isolated-vm/issues/243) and is resolved in branch `main`, new version was not yet published.
Compiling all of these modules is extremely slow (can reach a second when worker is busy), we should revisit this and perhaps switch to using a bundler and startup snapshots for isolates (a POC for that has been started in the `bundler` branch).

Create a bench test and stress the worker

---

packages/create-project/lib/index.js
packages/create-project/src/index.ts

Strip snipsync comments from package initializer generated files
They shouldn't have been there in the first place

feat(npm init): Strip snipsync comments from package initializer generated files

---

packages/client/src/index.ts
packages/create-project/samples/client-mtls-from-sample.ts
packages/create-project/samples/client.ts
packages/test-activities/src/index.ts
packages/test/src/bench.ts
packages/test/src/test-integration.ts
packages/worker/native/index.d.ts

See commit messages
Unify client and worker TLS configuration.
`namespace` in `ConnectionOptions` isn't used anywhere but `WorkflowClient` which is confusing behavior.
Ran the client TLS sample locally.
I'll update the documentation site soon.

Add `ConnectionOptions.tls` and move `ConnectionOptions.namespace` to `WorkflowOptions`.

---

packages/test/src/mock-native-worker.ts
packages/test/src/test-workflows.ts
packages/worker/native/index.d.ts
packages/worker/native/src/lib.rs
packages/worker/src/worker.ts
packages/worker/src/workflow.ts
packages/workflow/src/init.ts
packages/workflow/src/internals.ts

Updated the core submodule and made some of the preparations for sticky execution.
**NOTE**: We still do not support sharing a single core between multiple workers, I'll work on that in one of the next PRs.
Keep up with upstream core changes
Standard test suite
Not ATM

chore(core): Update core in prep for sticky execution

---

packages/core-bridge/package.json

Noticed that rust is not being cross compiled anymore and the latest published version does not include the pre-built binaries.
This is a regression introduced in #128.

fix: Fix cross compilation of rust code

---

packages/client/src/interceptors.ts
packages/client/src/workflow-client.ts
packages/client/src/workflow-options.ts
packages/test/src/test-integration.ts
packages/test/src/test-interceptors.ts

Closes #153
Also removes some `console.log` statements that somehow made their way into `main` and ensures all calls to `start` go through interceptors.

feat(client): Implement signalWithStart

---

packages/worker/src/isolate-builder.ts

Added a missing `mkdir()` call
If there's no activities, `registerActivities()` doesn't call `mkdir()`, so the `writeFileSync()` call will fail
1. Closes 

fix(worker): Avoid throwing error when there's no activities directory

---

packages/docs/docusaurus.config.js

Closes #115
Got an Algolia docsearch API key.
Configuration can be found here: https://github.com/algolia/docsearch-configs/blob/master/configs/nodejs-temporal.json

chore: Add algolia search to API reference

---

packages/interceptors-opentelemetry/src/workflow/index.ts
packages/test/src/interfaces/index.ts
packages/test/src/test-workflows.ts
packages/test/src/workflows/fail-unless-signaled-before-start.ts
packages/test/src/workflows/index.ts
packages/test/src/workflows/interceptor-example.ts
packages/test/src/workflows/internals-interceptor-example.ts
packages/test/src/workflows/trailing-timer.ts
packages/test/src/workflows/try-to-continue-after-completion.ts
packages/worker/src/utils.ts
packages/worker/src/worker.ts
packages/worker/src/workflow.ts
packages/workflow/src/index.ts
packages/workflow/src/interceptors.ts
packages/workflow/src/interfaces.ts
packages/workflow/src/internals.ts
packages/workflow/src/worker-interface.ts
packages/workflow/src/workflow.ts

BREAKING CHANGE: Workflow histories generated by old versions of the SDK
might break with non-determinism errors.
WorkflowInboundCallsInterceptor now has a `create` method to intercept
Workflow creation, the `WorkflowInput` interface was renamed
`WorkflowExecuteInput`.
Closes #202

feat(workflow)!: Process Workflow activations concurrently

---

.buildkite/docker/build-and-run-load.sh
package-lock.json
packages/interceptors-opentelemetry/package.json
packages/test/package.json
packages/test/tsconfig.json

I haven't confirmed this but I think our compilation is broken because we compile 2 projects (test and interceptors-opentelemetry) with shared project references.

chore: Fix TS project references

---

CONTRIBUTING.md
packages/client/src/errors.ts
packages/client/src/workflow-client.ts
packages/client/src/workflow-options.ts
packages/common/src/interfaces.ts
packages/common/src/workflow-handle.ts
packages/common/src/workflow-options.ts
packages/core-bridge/Cargo.lock
packages/test/src/interfaces/index.ts
packages/test/src/test-integration.ts
packages/test/src/workflows/continue-as-new-same-workflow.ts
packages/workflow/src/workflow.ts

BREAKING CHANGE: `WorkflowClient.result()` and
`WorkflowClient.createWorkflowStub()` override for attaching to an
existing Workflow now takes an object with `workflowId` and optional
`runId` instead of 2 strings.
`workflowDefaults` added to `WorkflowClientOptions`, if provided they
will be merged with per-method and per-handle options.
`WorkflowOptions` takes a `followRuns` boolean option which defaults to
`true`, it determines whether or not the client will follow the Workflow
execution chain when getting a Workflow's result.
Closes #222

feat(client): Follow Workflow execution chain

---

packages/core-bridge/Cargo.lock
packages/core-bridge/index.d.ts
packages/core-bridge/src/lib.rs
packages/worker/src/core.ts

Option to expose metrics endpoint for direct prometheus scraping
Many users will likely only care about prometheus and not otel collector
1. Relates to https://github.com/temporalio/sdk-core/issues/85
Verified server started properly

feat: Expose option to enable direct prometheus scraping

---

packages/workflow/src/workflow.ts

Already handled by core
Fixed node passing custom search attrs for child workflow command
1. Closes 

fix: Node should not set indexed_fields for child search attrs

---

packages/test/src/workflows/activity-failure.ts
packages/test/src/workflows/activity-failures.ts
packages/test/src/workflows/cancel-fake-progress.ts
packages/test/src/workflows/cancel-http-request.ts
packages/test/src/workflows/cancel-requested-with-non-cancellable.ts
packages/test/src/workflows/configured-activities.ts
packages/test/src/workflows/handle-external-workflow-cancellation-while-activity-running.ts
packages/test/src/workflows/http.ts
packages/test/src/workflows/multiple-activities-single-timeout.ts
packages/test/src/workflows/nested-cancellation.ts
packages/test/src/workflows/non-cancellable-shields-children.ts
packages/test/src/workflows/run-activity-in-different-task-queue.ts
packages/test/src/workflows/shared-promise-scopes.ts
packages/test/src/workflows/shield-awaited-in-root-scope.ts
packages/test/src/workflows/smorgasbord.ts
packages/workflow/src/index.ts
packages/workflow/src/workflow.ts

BREAKING CHANGE: The function's usage remains the same, only the name
was changed.
Before:
```ts
import { createActivityHandle } from '@temporalio/workflow';
import type * as activities from './activities';
const { greet } = createActivityHandle<typeof activities>({
startToCloseTimeout: '1 minute',
});
```
After:
```ts
import { proxyActivities } from '@temporalio/workflow';
import type * as activities from './activities';
const { greet } = proxyActivities<typeof activities>({
startToCloseTimeout: '1 minute',
});
```
Reasoning:
- Clarify that the method returns a proxy
- Avoid confusion with `WorkflowHandle`

feat(workflow)!: Rename `createActivityHandle` to `proxyActivities`

---

packages/test/src/workflows/async-fail-signal.ts
packages/test/src/workflows/cancel-fake-progress.ts
packages/test/src/workflows/cancel-http-request.ts
packages/test/src/workflows/child-workflow-termination.ts
packages/test/src/workflows/continue-as-new-same-workflow.ts
packages/test/src/workflows/fail-signal.ts
packages/test/src/workflows/fail-unless-signaled-before-start.ts
packages/test/src/workflows/interceptor-example.ts
packages/test/src/workflows/interrupt-signal.ts
packages/test/src/workflows/invalid-or-failed-queries.ts
packages/test/src/workflows/signal-target.ts
packages/test/src/workflows/smorgasbord.ts
packages/test/src/workflows/unblock-or-cancel.ts
packages/workflow/src/internals.ts
packages/workflow/src/workflow.ts

BREAKING CHANGE: The function's usage remains the same, only the name
was changed.
Before:
```ts
import { defineSignal, setListener, condition } from '@temporalio/workflow';
import { unblockSignal } from './definitions';
export const unblockSignal = defineSignal('unblock');
export async function myWorkflow() {
let isBlocked = true;
setListener(unblockSignal, () => void (isBlocked = false));
await condition(() => !isBlocked);
}
```
After:
```ts
import { defineSignal, setHandler, condition } from '@temporalio/workflow';
import { unblockSignal } from './definitions';
export const unblockSignal = defineSignal('unblock');
export async function myWorkflow() {
let isBlocked = true;
setHandler(unblockSignal, () => void (isBlocked = false));
await condition(() => !isBlocked);
}
```
Reasoning:
- It …

feat(workflow)!: Rename `setListener` to `setHandler`

---

packages/client/src/errors.ts
packages/client/src/workflow-client.ts
packages/test/src/test-integration.ts
packages/test/src/test-interceptors.ts
packages/test/src/test-workflow-cancellation.ts
scripts/registry.js

BREAKING CHANGE: Error handling for `WorkflowClient` and
`WorkflowHandle` `execute` and `result` methods now throw
`WorkflowFailedError` with the specific `TemporalFailure` as the cause.
The following error classes were renamed:
- `WorkflowExecutionFailedError` was renamed `WorkflowFailedError`.
- `WorkflowExecutionContinuedAsNewError` was renamed
`WorkflowContinuedAsNewError`.
Before:
```ts
try {
await WorkflowClient.execute(myWorkflow, { taskQueue: 'example' });
} catch (err) {
if (
err instanceof WorkflowExecutionFailedError &&
err.cause instanceof ApplicationFailure
) {
console.log('Workflow failed');
} else if (err instanceof WorkflowExecutionTimedOutError) {
console.log('Workflow timed out');
} else if (err instanceof WorkflowExecutionTerminatedError) {
console.log('Workflow …
```

feat(client)!: Use failure classes for WorkflowClient errors

---

packages/test/src/test-workflows.ts
packages/workflow/src/workflow.ts

Also clean up resources taken by the blocked condition.
Closes #363

fix(workflow): Cancel timer created by condition

---

packages/test/src/test-signals-are-always-delivered.ts
packages/test/src/workflows/index.ts
packages/test/src/workflows/signals-are-always-processed.ts
packages/worker/src/workflow/isolated-vm.ts
packages/workflow/src/worker-interface.ts

BREAKING CHANGE: This fixes a critical issue where the SDK was not processing histories in the right order.
Workflows that have been processed with older versions of the SDK may get stuck if the SDK is upgraded.

fix(workflow): Ensure signals are always processed

---

packages/client/src/workflow-client.ts
packages/client/src/workflow-options.ts
packages/common/src/workflow-options.ts
packages/test/src/load/starter.ts
packages/test/src/test-core.ts
packages/test/src/test-integration.ts
packages/test/src/test-interceptors.ts
packages/test/src/test-otel.ts
packages/test/src/test-signals-are-always-delivered.ts
packages/test/src/test-sinks.ts
packages/test/src/test-worker-from-bundle.ts
packages/test/src/test-worker-no-activities.ts
packages/test/src/test-worker-no-workflows.ts
packages/test/src/test-workflow-cancellation.ts
packages/workflow/src/interfaces.ts

This also removes the `WorkflowClientOptions.workflowDefaults`.
Reasoning:
- Workflow IDs should represent a meaningful business ID
- Workflow IDs can be used as an idempotency key when starting workflows from an external signal
- `workflowDefaults` were removed because their presence made `taskQueue` optional in `WorkflowOptions`, omitting it from both the defaults and options resulted in runtime errors where we could have caught those at compile time.\
Migration:
```ts
// Before
const client = new WorkflowClient(conn.service, { workflowDefaults: { taskQueue: 'example' } });
const handle = await client.start(myWorkflow, { args: [foo, bar] });
// After
const client = new WorkflowClient(conn.service);
const handle = await client.start(myWorkflow, {
args: [foo, bar],
taskQueue: 'example', …
```

feat!(client): Make workflowId required

---

.github/workflows/ci.yml

Not required anymore because:
- ts-node has added support for newer node versions
- removal of isolated-vm

test: Remove strict node version requirements

---

packages/test/src/workflows/child-workflow-signals.ts
packages/test/src/workflows/definitions.ts
packages/test/src/workflows/signal-target.ts
packages/workflow/src/workflow.ts

Apparently argument passing did not have test coverage and the rest argument in the data converter method prevented us from catching this earlier.
Before this fix, signal arguments sent from a workflow would be wrapped in an array.
```ts
await child.signal(someSignal, 1, '2');
```
Was received in the child workflow as:
```ts
wf.setHandler(someSignal, (num, str) => {
console.log(a, b) // [1, '2'], undefined
});
```

fix(workflow): Fix argument wrapping in array when signaling from Workflow

---

package-lock.json
packages/create-project/package.json
packages/create-project/src/helpers/git.ts

Fixes issue where `fs-extra` is incompatible with ESM as reported on slack.
Closes #408

chore: Don't use fs-extra in create-project

---

packages/common/src/interfaces.ts

Adds comments indicating why the seemingly unused generics are useful.
I went through a whole investigation trying to remove them, only to have @sw-yx show me that the `Handler` type does, in fact, use the generics well.
1. How was this tested:
`npm run build` / `npm run build.watch`

Added comments for unused query and signal generics

---

.github/workflows/ci.yml

It's otherwise impossible to get external contributions to pass CI

test: Ignore github actions jobs that require secrets for external committers

---

packages/client/src/workflow-client.ts

Added `T extends Workflow = Workflow` defaults for `WorkflowHandle` & co.
This way workflow handle type declarations don't need to pass around their workflow type.
1. Closes #418

Defaulted WorkflowHandle T generics to Workflow

---

packages/common/src/activity-options.ts
packages/common/src/converter/types.ts
packages/common/src/failure.ts
packages/common/src/interceptors.ts
packages/common/src/time.ts
packages/common/src/type-helpers.ts
packages/common/src/workflow-options.ts
packages/worker/src/workflow/vm.ts
packages/workflow/src/interceptors.ts
packages/workflow/src/interfaces.ts
packages/workflow/src/internals.ts
packages/workflow/src/worker-interface.ts

This is now possible because we're using vm instead of isolated-vm.
- Greatly reduce workflow bundle size - our test bundle size went down from 2.77MB to 0.73MB
- Step 1 in supporting custom data converters

feat: Remove proto usage from workflow runtime

---

packages/test/src/run-a-worker.ts
packages/test/src/run-a-workflow.ts
packages/test/src/test-integration.ts
packages/test/src/test-workflow-unhandled-rejection-crash.ts
packages/test/src/test-workflows.ts
packages/test/src/workflows/index.ts
packages/test/src/workflows/unhandled-rejection.ts
packages/worker/src/index.ts
packages/worker/src/worker.ts
packages/worker/src/workflow/bundler.ts
packages/worker/src/workflow/threaded-vm.ts
packages/worker/src/workflow/vm.ts
packages/worker/src/workflow/workflow-worker-thread.ts
packages/workflow/src/worker-interface.ts

This PR makes the best effort to associate unhandled rejections from workflow code to a specific runId.
It also makes the unhandled rejection behavior consistent between node 14 and 16 and propagates failure back to the user.
Previously, in node 16 the process would crash and in node 14 we would incorrectly ignore rejections leading to unexpected workflow behavior (see the correct behavior in the added tests).

feat(workflow): Handle unhandled rejections in workflow code

---

packages/common/src/failure.ts
packages/test/src/test-integration.ts
packages/test/src/test-interceptors.ts
packages/test/src/test-workflows.ts
packages/test/src/workflows/async-fail-signal.ts
packages/test/src/workflows/fail-signal.ts
packages/test/src/workflows/interceptor-example.ts
packages/test/src/workflows/interrupt-signal.ts
packages/test/src/workflows/throw-async.ts
packages/test/src/workflows/try-to-continue-after-completion.ts
packages/test/src/workflows/workflow-cancellation-scenarios.ts
packages/workflow/src/internals.ts

BREAKING CHANGE: Before this change throwing an error in a Workflow
would cause the Workflow execution to fail. After the change only the
Workflow task fails on random errors.
To fail the Workflow exection throw `ApplicationFailure.nonRetryable`.
To make other error types non retryable use the
`WorkflowInboundCallsInterceptor` `execute` and `handleSignal` methods
to catch errors thrown from the Workflow and convert them to non
retryable failures, e.g:
```ts
class WorkflowErrorInterceptor implements WorkflowInboundCallsInterceptor {
async execute(input: WorkflowExecuteInput, next: Next<WorkflowInboundCallsInterceptor, 'execute'>): Promise<unknown> {
try {
return await next(input);
} catch (err) {
if (err instanceof MySpecialNonRetryableError) {
throw …
```

feat(workflow)!: Make random workflow errors retryable

---

packages/test/src/test-integration.ts
packages/test/src/test-workflows.ts
packages/test/src/workflows/interrupt-signal.ts
packages/test/src/workflows/throw-async.ts
packages/workflow/src/internals.ts

Makes `ApplicationFailure.retryable` fail the workflow execution and not the task as intended, this was wrongly implemented in #429.

fix: Fix workflow retryable Application failure fails execution

---

packages/workflow/src/workflow.ts

I think `options`'s type should have `WithWorkflowArgs`. It does in the `workflowFunc` overload of `startChild`
Reported by @sw-yx  https://temporaltechnologies.slack.com/archives/C01FT8U10GK/p1642035091026400

fix(workflow): Fix startChild options type

---

packages/core-bridge/common.js
packages/core-bridge/index.js
packages/core-bridge/package.json
packages/core-bridge/scripts/build.js
scripts/clean.js

- `core-bridge` can now be imported in a different OS than the one the SDK was installed in.
- Closes https://github.com/temporalio/sdk-typescript/issues/457

feat(core): Make Core portable

---

packages/test/src/test-replay.ts
packages/worker/src/core.ts
packages/worker/src/index.ts
packages/worker/src/worker.ts

The `getWorkflowExecutionHistory` grpc call returns `GetWorkflowExecutionHistoryResponse` with a `history: IHistory` attribute. We should support this use case.

feat: Accept IHistory for history replay

---

packages/client/src/async-completion-client.ts
packages/client/src/errors.ts
packages/client/src/interceptors.ts
packages/client/src/types.ts
packages/client/src/workflow-client.ts
packages/common/src/errors.ts
packages/test/src/test-integration.ts
packages/test/src/workflows/continue-as-new-to-different-workflow.ts
packages/workflow/src/errors.ts

In addition:
- Adds safety to `terminate` and `cancel` so handles created with `start` can't accidentally affect workflows that are not part of the same execution chain
- Adds optional `firstExecutionRunId` param to `getHandle` for added safety
- Closes #464
- Closes #377
- Closes #365

feat(client): Use `runId` only in handles created with `getHandle`

---

CONTRIBUTING.md
packages/common/src/failure.ts
packages/common/src/type-helpers.ts
packages/test/src/test-integration.ts
packages/test/src/workflows/index.ts
packages/test/src/workflows/throw-object.ts
packages/test/src/workflows/unhandled-rejection.ts

Implements all I suggested in #462  except for more specific `source`, which I think would require passing more info to `errorToFailure`. I'd like to get to that later.
This change could be breaking: if a user is checking whether `failure.message === 'Error: orig message'`, it won't catch the new `failure.message = 'orig message'`. I think the old behavior that added the `Error: ` was unintentional—at the end of `errorToFailure`, the `instanceof Error` failed because the Error was coming from the vm, so `String(err)` was used.

fix!: Improve failure details, fixes #462

---

CHANGELOG.md
packages/core-bridge/Cargo.lock

- Replay mock client wasn't allowing completes ([#269](https://github.com/temporalio/sdk-core/pull/269))
- Fix heartbeats not flushing on activity completion ([#266](https://github.com/temporalio/sdk-core/pull/266))

fix: Upgrade Core to receive recent fixes

---

packages/interceptors-opentelemetry/src/client/index.ts
packages/interceptors-opentelemetry/src/instrumentation.ts
packages/interceptors-opentelemetry/src/worker/index.ts
packages/interceptors-opentelemetry/src/workflow/index.ts
packages/test/src/test-otel.ts
packages/workflow/src/index.ts
packages/workflow/src/interfaces.ts

Also do not set an error on the otel span when the interceptor catches `ContinueAsNew`.
Closes #397

fix(workflow): Fix ContinueAsNew error message and name

---

packages/worker/src/workflow/bundler.ts

so its found in a yarn workspaces monorepo
Wrapped `ts-loader` in a call to `require.resolve()`
So its correctly located in a `yarn workspaces` monorepo
1. Closes 
I edited the published source code to make this change and re-ran the sample app I was working in.
N/A

Resolve ts-loader

---

CONTRIBUTING.md

Decompressing/copying before `git clean` resulted in no `packages/core-bridge/releases/` directory.

docs: Fix order in publishing script

---

packages/common/src/failure.ts
packages/worker/src/worker.ts

Before this fix, the ApplicationFailures returned by the Worker in these
two circumstances were not retryable:
- Activity not found
- Failed to parse Activity args
Closes #521

fix(worker)!: Mark activity errors retryable

---

.github/workflows/ci.yml
packages/test/src/test-worker-activities.ts
packages/test/src/test-worker-lifecycle.ts

Without a `cancel.reason`, the test hangs after:
Just confirming: even though the proto says reason is optional, it should always be there, and worker should throw & fail when it's not?

fix: Add reason to cancelation tasks in tests

---

package-lock.json
packages/common/src/failure.ts
packages/test/src/test-workflows.ts
packages/worker/package.json
packages/worker/src/workflow/vm.ts
packages/workflow/src/worker-interface.ts

Use microtaskMode=afterEvaluate to ensure `isolateExecutionTimeoutMs`
includes microtask processing too.

fix(workflow): Properly wait for vm microtasks

---

packages/client/src/types.ts
packages/client/src/workflow-client.ts
packages/internal-non-workflow-common/src/codec-helpers.ts
packages/internal-workflow-common/src/time.ts
packages/test/src/integration-tests.ts
packages/test/src/test-integration-codec.ts

feat(client)!: Return a friendly type from handle.describe()

---

package-lock.json
packages/client/package.json
packages/client/src/connection.ts
packages/client/src/grpc-retry.ts
packages/client/src/index.ts

- Upgrade grpc-js dependency to ^1.5.7
- Export `*` from `grpc-retry`
- Use more exact type for `ConnectionOptions.channelArgs`
- Set `grpc.default_authority` channel arg if `serverNameOverride` is
provided (closes #455)

feat(client): Minor connection improvements

---

packages/client/src/workflow-client.ts
packages/common/src/converter/payload-converter.ts
packages/test/src/integration-tests.ts
packages/workflow/src/workflow.ts

Temporal doesn't support Null or Binary Payloads for search attributes.

fix: Use JsonPayloadConverter for search attributes

---

packages/client/src/index.ts
packages/client/src/workflow-options.ts
packages/common/src/index.ts
packages/workflow/src/index.ts

Fixes #557
Alternatively, we could `export * from '@temporalio/common'` in client and workflow?

fix: Export more from client, workflow, and common

---

.github/workflows/ci.yml
CHANGELOG.md

- chore: Update CHANGELOG for 0.19.2
- Point CI at next branch of samples-typescript

chore: Update CHANGELOG for 0.19.2

---

package-lock.json
packages/worker/package-lock.json
packages/worker/package.json
packages/worker/src/workflow/bundler.ts

- Fixes #534
Background: https://github.com/temporalio/sdk-typescript/issues/534#issuecomment-1067920797
- Verified that setting target in playground to ES2017 removed `_asyncToGenerator` from compiled JS
- Verified that setting target in `bundler.js` to es2017 stopped the `Module not found: Error: Can't resolve 'regenerator-runtime'` error from happening
The only thing in ES2017 missing from Node 14+ is [Atomics.wait](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics/wait):
https://node.green/#ES2017

feat(worker): Use swc-loader instead of ts-loader (#525)

---

.gitignore
packages/activity/src/index.ts
packages/internal-workflow-common/src/activity-options.ts
packages/test/src/test-local-activities.ts
packages/test/src/workflows/local-activity-testers.ts
packages/worker/src/worker.ts
packages/workflow/src/interceptors.ts
packages/workflow/src/internals.ts
packages/workflow/src/worker-interface.ts
packages/workflow/src/workflow.ts

BREAKING CHANGE: ActivityOptions no longer takes a `namespace`

feat!: Implement local activities

---

packages/test/src/integration-tests.ts
packages/test/src/test-workflows.ts
packages/test/src/workflows/index.ts
packages/test/src/workflows/signal-handlers-clear.ts
packages/workflow/src/workflow.ts

1. Fixed a heap overflow issue in `setHandler(signal, handler)` when handler is `undefined` and there are buffered signals for that signal name.
2. Changed the signature of `setHandler(...)` to indicate that `handler` can be `undefined` (in order to clear up previously configured handler for that signal name).
Refer to #612 for discussion.
1. Closes #612 
2. **How was this tested?** I added appropriate integration test
3. **Any docs updates needed?** No doc that I know of that should be updated, but it could be useful to add a sample demonstrating this use case (for example based on examples in #612 or code in unit test).

Fix: Make sure signal handlers can be cleared

---

packages/docs/docusaurus.config.js
packages/docs/package-lock.json

Fix #544
Added samples-typescript as a source for snipsync. This way our docs can reference snippets from samples-typescript.
There are a few places in the API docs where we want to use snippets from samples-typescript. There shouldn't be any problem with recursive dependencies since snipsync doesn't run `npm install` in the samples-typescript repo.
1. Closes #544
Snippets now show up on my local:

make snipsync pull from samples-typescript

---

packages/test/src/test-local-activities.ts
packages/test/src/test-worker-lifecycle.ts
packages/worker/src/runtime.ts
packages/worker/src/worker-options.ts
packages/worker/src/worker.ts

Makes more sense to put it on the singleton `Runtime` instead of a per-Worker

feat!(worker): Move shutdownSignals to RuntimeOptions

---

packages/interceptors-opentelemetry/src/workflow/runtime.ts
packages/test/src/test-otel.ts
packages/workflow/src/workflow.ts

fix: Do not patch global object in otel runtime if not in workflow context

---

packages/test/src/load/all-scenarios.ts

Not used to running `spawnSync`, luckily I caught it early

test: Actually fail stress test when child fails

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
.github/workflows/stress.yml
packages/testing/scripts/download-test-server.mjs

CI is rate limited by Github REST API:
```
@temporalio/testing: > node ./scripts/download-test-server.mjs
@temporalio/testing: internal/process/esm_loader.js:74
@temporalio/testing:     internalBinding('errors').triggerUncaughtException(
@temporalio/testing:                               ^
@temporalio/testing: HTTPError: Response code 403 (rate limit exceeded)
```
[build-and-test (14, macos-latest)](https://github.com/temporalio/sdk-typescript/runs/6314570053?check_suite_focus=true#logs)
Currently on the default anonymous 60 requests per hour per IP address.
Authenticate, to get 1k requests per hour per repo:
https://docs.github.com/en/rest/overview/resources-in-the-rest-api#requests-from-github-actions

chore(test): Use GITHUB_TOKEN for higher rate limit

---

packages/test/src/workflows/cancel-fake-progress.ts
packages/test/src/workflows/long-history-generator.ts

Fixes this flake:
```
Starter encountered error WorkflowFailedError: Workflow execution failed
2022-05-05T19:38:26.9393036Z     at WorkflowClient.result (/home/runner/_work/sdk-typescript/sdk-typescript/packages/client/lib/workflow-client.js:205:23)
2022-05-05T19:38:26.9394301Z     at runMicrotasks (<anonymous>)
2022-05-05T19:38:26.9395092Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-05-05T19:38:26.9395783Z     at async Promise.all (index 0)
2022-05-05T19:38:26.9397052Z     at async runWorkflow (/home/runner/_work/sdk-typescript/sdk-typescript/packages/test/lib/load/starter.js:73:5) {
2022-05-05T19:38:26.9397944Z   cause: [TemporalFailure: Activity execution failed] {
2022-05-05T19:38:26.9398714Z     cause: [TimeoutFailure: activity Heartbeat timeout] { …
```

test: Fix activity heartbeat timeout crashing nightly

---

packages/test/src/test-worker-activities.ts
packages/test/src/test-worker-heartbeats.ts
packages/worker/src/activity.ts
packages/worker/src/worker.ts

Discovered in nightly tests: https://github.com/temporalio/sdk-typescript/runs/6312107494
Symptom was this fatal error:
```
[TransportError: Unhandled grpc error when completing activity: Status { code: InvalidArgument, message: "Failure must have ApplicationFailureInfo.", metadata: MetadataMap { headers: {"content-type": "application/grpc"} }, source: None }]
```

fix(activity): Fix Activity resolved as cancelled in unsupported situations

---

packages/test/src/test-workflows.ts
packages/test/src/workflows/index.ts
packages/test/src/workflows/scope-cancelled-while-waiting-on-external-workflow-cancellation.ts
packages/workflow/src/workflow.ts
scripts/registry.js

Wrapped this functionality in a patch to avoid breaking history compatibility.
This patch should be deprecated in a few months and eventually deleted.

fix(workflow): Propagate scope cancellation while waiting on ExternalWorkflowHandle cancellation

---

docs/data-converter.md
packages/common/src/converter/data-converter.ts
packages/common/src/converter/payload-codec.ts
packages/internal-non-workflow-common/src/codec-helpers.ts
packages/internal-non-workflow-common/src/data-converter-helpers.ts
packages/test/src/integration-tests.ts
packages/test/src/test-custom-payload-codec.ts
packages/test/src/test-worker-heartbeats.ts
packages/worker/src/worker.ts
packages/worker/src/workflow-codec-runner.ts

`DataConverter.payloadCodec` was changed to plural:
```ts
export interface DataConverter {
...
payloadCodecs?: PayloadCodec[];
}
```
So it's easier to provide multiple codecs (than the current solution, creating a CompositeCodec).
Wrote in a couple bugs that took a bit to track down! 
- Fixes: https://github.com/temporalio/sdk-typescript/issues/595

feat: Allow for multiple DataConverter.payloadCodecs

---

packages/client/src/workflow-client.ts
packages/test/src/integration-tests.ts
packages/test/src/test-sinks.ts
packages/test/src/workflows/child-workflow-cancel.ts
packages/test/src/workflows/child-workflow-invoke.ts
packages/test/src/workflows/child-workflow-signals.ts
packages/test/src/workflows/child-workflow-termination.ts
packages/workflow/src/workflow-handle.ts
packages/workflow/src/workflow.ts

`originalRunId` is a concept related to resetting workflows. None of the instances of `originalRunId` I found in the SDK seem to do with resetting, so I changed them all to `firstExecutionRunId`.

fix!: Use firstExecutionRunId instead of originalRunId

---

.github/workflows/nightly.yml
.github/workflows/stress.yml
packages/core-bridge/src/lib.rs
packages/test/src/activities/index.ts
packages/test/src/load/all-in-one.ts
packages/test/src/load/all-scenarios.ts
packages/test/src/load/args.ts
packages/test/src/load/starter.ts
packages/test/src/payload-converters/payload-converter.ts
packages/test/src/payload-converters/proto-payload-converter.ts
packages/test/src/test-custom-payload-converter.ts
packages/test/src/test-payload-converter.ts
packages/test/src/test-sinks.ts
packages/test/src/workflows/args-and-return.ts
packages/test/src/workflows/index.ts
packages/test/src/workflows/log-sink-tester.ts
packages/testing/src/child-process.ts
packages/worker/src/activity.ts
packages/worker/src/worker.ts

- Record memory usage in stress tests
- Run nightly at night (PST)
- Don't block runtime loop when creating new client
- Don't include proto converter in test workflows `index.ts` - cuts the test bundle size by half
- Fix inflight activity tracking
- Expose `WorkerStatus.numHeartbeatingActivities`
- Handle ShutdownError by name - closes #614 
- Fix TS initiated activity cancellation not creating a proper `ApplicationFailure`
- Closes #667

fix: Various improvements and fixes

---

packages/internal-workflow-common/src/retry-policy.ts
packages/test/src/test-retry-policy.ts

Added a quick check that `maximumAttempts` is a number using [`Number.isInteger()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger). This check explicitly excludes numbers like 3.1415 and `Number.POSITIVE_INFINITY`.
`maximumAttempts` should always be an integer, doesn't make much sense for it to have a decimal component. And `maximumAttempts = 0` is the preferred alternative for `maximumAttempts = Number.POSITIVE_INFINITY`
1. Closes #656
Added a couple of test cases

fix: Validate that RetryPolicy maximumAttempts is an integer

---

packages/client/src/types.ts
packages/client/src/workflow-client.ts
packages/internal-workflow-common/src/interfaces.ts
packages/internal-workflow-common/src/workflow-options.ts
packages/test/src/workflows/return-search-attributes.ts
packages/test/src/workflows/upsert-and-read-search-attributes.ts
packages/worker/src/worker.ts
packages/workflow/src/interfaces.ts
packages/workflow/src/workflow.ts

To prevent mixed-type array at type level. Keeping runtime check for JS users.
Background: https://github.com/temporalio/sdk-python/pull/43#discussion_r894771799
Not labeling as breaking, since it can be included in the same release as SA feature.

refactor: Make SearchAttributesValue an array

---

packages/test/src/test-worker-from-bundle.ts
packages/worker/src/workflow/bundler.ts

Instead of logging a warning, throw an error when importing a node built-in
If you `import path from 'path'`, you get a warning, which is easy to miss in the log output. Then you end up with a hard-to-diagnose runtime error if you use `path.join()`:
```
2022-06-07T18:54:11.935439Z  WARN temporal_sdk_core::worker: Failing workflow activation, run_id: "c9db39d3-851f-4386-bd8e-682b679e82cb", failure: Failure { failure: Some(Failure { message: "path__WEBPACK_IMPORTED_MODULE_1___default(...).join is not a function", source: "TypeScriptSDK", stack_trace: "TypeError: path__WEBPACK_IMPORTED_MODULE_1___default(...).join is not a function\n    at example (webpack-internal:///./src/workflows.ts:16:68)", cause: None, failure_info: None }) }
```
Right now, I'm thinking that throwing an error is better …

fix(Worker): Throw error when importing a node built-in module from a Workflow

---

packages/worker/src/connection.ts

Recreate and rethrow TransportErrors
Better stack traces and debugging. I originally ran into this issue because when I'd start a worker without a Temporal server running, I'd get the `[TransportError: transport error]` error with no stack trace.
I originally took a look at #582, but I haven't been able to figure out enough about the core SDK to figure out how to improve the error message. However, adding [async stack traces](https://thecodebarbarian.com/async-stack-traces-in-node-js-12) is fairly easy as long as we're willing to create a new `TransportError` instance in our async function. With this change, if I start the hello-world sample without a Temporal server running, I get the below error (Node v16.14):
```
TransportError: transport error
at Function.create …
```

fix: Recreate TransportErrors in initial connection to provide better stack traces

---

packages/common/src/failure.ts
packages/test/src/activities/failure-tester.ts
packages/test/src/workflows/activity-failures.ts

Use `err.constructor.name` instead of `err.name` by default, since `.name` is still 'Error' for classes that extend Error.
1. Closes #637

fix: Use error constructor name as `applicationFailureInfo.type`

---

packages/worker/src/worker.ts

Because Jest messes up with imports and modules get re-evaluated in different contexts, our Activity function check doesn't work when the function is a mock `jest.fn()`.
https://temporalio.slack.com/archives/C01DKSMU94L/p1655374964331519

feat: Support Jest mock Activity functions

---

packages/test/src/test-custom-payload-codec.ts
packages/test/src/test-custom-payload-converter.ts
packages/test/src/test-interceptors.ts
packages/test/src/test-local-activities.ts
packages/test/src/test-otel.ts
packages/test/src/test-payload-converter.ts
packages/test/src/test-signals-are-always-delivered.ts
packages/test/src/test-sinks.ts
packages/test/src/test-testenvironment.ts
packages/test/src/test-worker-debug-mode.ts
packages/test/src/test-worker-from-bundle.ts
packages/test/src/test-worker-heartbeats.ts
packages/test/src/test-worker-no-activities.ts
packages/test/src/test-worker-no-workflows.ts
packages/worker/src/worker.ts
packages/worker/src/workflow/bundler.ts

Useful helper especially in tests.
Usage:
```ts
const worker = await Worker.create(opts);
// Wait on an async function
await worker.runUntil(async () => {
client.execute(someWorkflow, wopts);
});
// -- OR --
// Wait on a promise
await worker.runUntil(client.execute(someWorkflow, wopts));
```

feat(worker): Add `runUntil` method

---

packages/core-bridge/src/errors.rs
packages/core-bridge/src/lib.rs
packages/test/src/test-native-connection.ts

Fixed error reporting to use debug instead of display formatting, which was hiding detail. Also cleaned up error conversion code.
Detail good.
1. Closes 

Fix error details being dropped when returning core errors

---

packages/core-bridge/index.d.ts
packages/core-bridge/src/lib.rs
packages/test/src/test-native-connection-headers.ts
packages/worker/src/connection-options.ts
packages/worker/src/connection.ts

To use the same term as `@temporalio/client.Connection`
BREAKING CHANGE:
- `NativeConnectionOptions.headers` was renamed to `NativeConnectionOptions.metadata`
- `NativeConnection.updateHeaders` was renamed to `NativeConnection.updateMetadata`

feat(worker)!: Rename headers to metadata for `NativeConnection`

---

.github/workflows/ci.yml
.github/workflows/stress.yml

- add npm logs for https://github.com/temporalio/sdk-typescript/issues/496#issuecomment-1166099476
- always upload nightly worker logs, so we have green output to compare to

chore: Add more build artifacts for debugging

---

packages/test/src/integration-tests.ts
packages/test/src/test-sinks.ts
packages/test/src/test-workflows.ts
packages/test/src/workflows/log-sink-tester.ts
packages/worker/src/worker.ts
packages/worker/src/workflow/vm.ts
packages/workflow/src/interfaces.ts
packages/workflow/src/internals.ts
packages/workflow/src/worker-interface.ts
packages/workflow/src/workflow.ts

We want Tasks to be as much of an implementation detail as possible so that normally devs don't have to know/think about them. 
Added note to `workflowInfo()` about recommended usage due to the fact that fields change (and which fields change will also change).

refactor(workflow)!: Move TaskInfo to WorkflowInfo

---

packages/activity/src/index.ts
packages/create-project/src/helpers/samples.ts
packages/docs/docusaurus.config.js
packages/worker/src/index.ts

BREAKING CHANGE: If you were importing any of these from `@temporalio/activity`, instead import from `@temporalio/common`: `ValueError, PayloadConverterError, IllegalStateError, WorkflowExecutionAlreadyStartedError, WorkflowNotFoundError`

refactor!: Update activity and worker exports

---

CHANGELOG.md

Rendered: https://github.com/temporalio/sdk-typescript/blob/d07cb99976d67da37645e9d5d40ef23f621fd9c8/CHANGELOG.md

chore: Update CHANGELOG for v1.0.0 🥳

---

CONTRIBUTING.md
packages/internal-workflow-common/src/retry-policy.ts
packages/test/src/test-retry-policy.ts

Edit: Allow user to provide `maximumAttempts: Number.POSITIVE_INFINITY` and drop it, since it's the default.
---
In the changelog we suggest using 0 for Infinity, but are currently throwing when 0 is passed.

fix: Allow `RetryPolicy.maximumAttempts: Number.POSITIVE_INFINITY`

---

packages/worker/src/worker.ts

Remove a call to `end()` the `workflow.process` span in a worker.
Since this span is coming from an `instrument` call, it will be guaranteed to end once the function given to instrument ends, so we should not call `end`.
Ending a span twice results in some logging that is undesirable in production scenarios ([see otel](https://github.com/open-telemetry/opentelemetry-js/blob/cfda625e83a164c9e19745392879c32aedcfe76f/packages/opentelemetry-sdk-trace-base/src/Span.ts#L239)).
Closes #781

fix: Prevent ending a worker span twice

---

package-lock.json
packages/testing/package.json
packages/testing/src/index.ts

Removes use of dynamic import by downgrading to pre-ESM-only version of `get-port`.
So that users don't have to support dynamic imports in their test build system.

fix: Avoid using dynamic import in /testing

---

package-lock.json
packages/common/package.json

So that multiple versions of protobufjs aren't installed (1.0.2 used v6). Hopefully avoids this issue https://community.temporal.io/t/worker-error-with-mul-is-not-a-function/5573/13

fix: Update `proto3-json-serializer` to `^1.0.3`

---

packages/common/src/failure.ts

- Fixes #752
```ts
ApplicationFailure.create({ cause })
```
- Makes fields optional and allows them to be `undefined | null`, so you can do:
```ts
new ApplicationFailure()
new ApplicationFailure(null, null, null, null, cause)
new ApplicationFailure(undefined, undefined, undefined, undefined, cause)
ApplicationFailure.retryable()
ApplicationFailure.retryable(null, null, ...details)
```
DX

feat(common): Improve ApplicationFailure arguments; add create

---

packages/proto/protos/root.js
packages/testing/scripts/compile-proto.mjs

Forcibly inject `long` into `protobufs` objects.
Reference: https://github.com/protobufjs/protobuf.js/issues/1745#issuecomment-1200319399
`protobufjs/light` delegates loading of `long` to the `@protobufjs/inquire` package. Now, `@protobufjs/inquire` itself does not declare a dependency on long in its `package.json`.
This pattern works in most environment, thanks to the way traditional package managers lay out their `node_modules` directory, but is forbidden by Yarn 3 and PNPM, though the extend to which they goes in applying that restriction depend on various configuration item... Yarn 3's PnP is essentially the strictest of all.
In practice, that means that in some environement, `protobufjs` fails to load `long`. It fallbacks to create number objects that are very similar to the objects …

fix: Help protobufjs find 'long' in Yarn PnP (#810)

---

packages/worker/src/worker-options.ts
packages/worker/src/worker.ts

Added the ones @cretz suggested as well as `stickyQueueScheduleToStartTimeout` and `maxCachedWorkflows`

fix(worker): Remove unnecessary `ReplayWorkerOptions`

---

packages/test/src/test-bundler.ts
packages/test/src/test-local-activities.ts
packages/test/src/test-workflows.ts
packages/worker/src/index.ts
packages/worker/src/worker-options.ts
packages/worker/src/worker.ts
packages/worker/src/workflow/bundler.ts
packages/worker/src/workflow/threaded-vm.ts
packages/worker/src/workflow/vm.ts
packages/worker/src/workflow/workflow-worker-thread.ts
packages/worker/src/workflow/workflow-worker-thread/input.ts

Makes it possible to actually use breakpoints in workflow code.
- Use inline source maps
- Set script filename to be an absolute path, matching the original filename stored in the source map
- Make sure different workflow bundles get different filename
- Preload and cache the script object
1. Closes #795
- Breakpoints during tests execution (vscode)
- Verdaccio build on local examples (vscode)
- Verdaccio build on local examples (chrome's debugger)
- Chrome's debugger don't know much about nodejs worker threads. It however works properly when running a worker in single thread mode (ie. `debugMode = true`)

fix(workflow)!: Make breakpoints work inside workflow isolate context

---

packages/worker/src/worker-options.ts
packages/worker/src/worker.ts
packages/worker/src/workflow/bundler.ts

NOTE: We now prefer taking the bundle over workflowsPath which is the correct behavior and what users *should* expect.
Also warning that workflow interceptors are ignored when using a bundle.

fix: Warn instead of throwing when getting `workflowBundle` with `workflowsPath` and `bundlerOptions`.

---

package-lock.json
package.json
packages/nyc-test-coverage/package.json
packages/nyc-test-coverage/tsconfig.json
packages/test/tsconfig.json

#839
When I added `    "build": "tsc --build",` to nyc package.json, I got this:
hence adding to `/test/tsconfig.json` instead.

fix: Build `nyc-test-coverage` package, fixes #839

---

.vscode/settings.json
docs/debug-replay.mermaid
packages/test/src/debug-replayer.ts
packages/test/src/workflows/http.ts
packages/worker/src/debug-replayer/client.ts
packages/worker/src/debug-replayer/inbound-interceptor.ts
packages/worker/src/debug-replayer/index.ts
packages/worker/src/debug-replayer/outbound-interceptor.ts
packages/worker/src/debug-replayer/worker-thread.ts
packages/worker/src/debug-replayer/workflow-notifier.ts
packages/worker/src/index.ts
packages/worker/src/worker.ts

Will be used in the VS Code debugger extension.
See [`.vscode/settings.json`](https://github.com/bergundy/sdk-typescript/blob/0205f0b11a815e6a3aff0fc4c25fe6b651a95db5/.vscode/settings.json) and [`debug-replayer.ts`](https://github.com/bergundy/sdk-typescript/blob/0205f0b11a815e6a3aff0fc4c25fe6b651a95db5/packages/test/src/debug-replayer.ts) for reference.

feat: Implement entrypoint for debug replayer

---

packages/client/src/workflow-client.ts
packages/client/src/workflow-options.ts
packages/test/src/integration-tests.ts

when calling `signalWithStart`

fix(client): Only require `signalArgs` when needed

---

CHANGELOG.md

[rendered](https://github.com/temporalio/sdk-typescript/blob/release-v1.3.0/CHANGELOG.md#130---2022-09-20)

chore: Add v1.3.0 to CHANGELOG

---

.github/workflows/ci.yml
packages/client/src/workflow-client.ts
packages/test/src/integration-tests.ts

As of 1.18 the server deletes search attributes with empty array values, mimic that behavior when getting the `describe` response from older servers and update CI to use 1.18.

feat: Delete search attributes with empty array values in describe() response

---

packages/client/src/grpc-retry.ts
packages/test/src/test-client-connection.ts

Also backs off more on RESOURCE_EXHAUSTED errors (https://github.com/temporalio/sdk-features/issues/96)
Technically a breaking change but affects only really advanced options.

feat(client)!: Make client gRPC retry more configurable

---

packages/client/src/grpc-retry.ts
packages/common/src/converter/failure-converter.ts
packages/core-bridge/Cargo.lock
packages/core-bridge/index.d.ts
packages/core-bridge/src/conversions.rs
packages/proto/scripts/compile-proto.js
packages/test/src/test-workflows.ts
packages/worker/src/index.ts
packages/worker/src/worker-options.ts
packages/worker/src/worker.ts
packages/worker/src/workflow/bundler.ts

[Fix double import of long in generated proto TS files](https://github.com/temporalio/sdk-typescript/commit/4c4b0d9609ec892227163a93f3751ed593bb362d)
[Fix bundler with default workflow interceptors](https://github.com/temporalio/sdk-typescript/commit/179c05ab6220910c590e653129f873fff3225ebc)
[Label grpc-retry API as experimental](https://github.com/temporalio/sdk-typescript/commit/cf77e2346a30ce5d6c35aba023a5091a7c9fb6a6)
[Upgrade core, add support for OTEL metric temporality](https://github.com/temporalio/sdk-typescript/commit/882f13aaf2b70b358ea62ea02dd3c427bfc10682)
[Limit eager activity requests to 3](https://github.com/temporalio/sdk-typescript/commit/2658bad3e228637884a21bfe37648ce69ce34c07)
[Make the failure-converter code …

Bunch of small stuff

---

.github/workflows/ci.yml
packages/worker/src/worker.ts

User complained in slack that the previous regex was causing `RangeError: Maximum call stack size exceeded`.
I tried a couple alternatives, the chosen one and splitting the lines first, ran 10,000 iterations and got these results:
- Split first: 12.371s
- New regex: 4.797s
- Original regex: 36.535s

Improve regex for extracting source map

---

packages/client/src/workflow-client.ts

Tested manually but this fixes an issue reported on slack where the client throws when the test server returns a result with absent history.

fix(client): Handle test server absent history when waiting for workflow result

---

CHANGELOG.md

I'm going to publish this version with `--exact`.
Rather not take anymore chances where we break our own internal packages like we did in 1.4.0.

Update changelog for 1.4.1

---

packages/nyc-test-coverage/src/index.ts

Re: temporalio/temporal-pendulum#21
Don't check for `__coverage__` when the module loads, but when the `augment()` methods run.
Jest quirks: `__coverage__` isn't set when the module first loads.
1. Closes 

fix: Delay checking for __coverage__ until helpers run because __coverage__ is undefined when Jest starts

---

packages/test/src/test-worker-lifecycle.ts
packages/worker/src/runtime.ts
packages/worker/src/worker.ts

In `Runtime`, deny adding more shutdown hooks once a shutdown signal has been received.
Avoid a race situation where a process might be sent a shutdown signal, but some worker has not yet registered its shutdown hook, causing the worker to never terminate.
1. Closes #909

fix(worker): avoid a race in shutdown hooks

---

packages/common/src/converter/failure-converter.ts

Technically breaking but this API is experimental.
If we want failure conversion to be fully customizable we need to allow any error to be returned here.

fix: Loosen FailureConverter.errorToFailure return type

---

packages/common/src/converter/failure-converter.ts
packages/common/src/internal-non-workflow/codec-helpers.ts
packages/test/src/test-workflows.ts
packages/workflow/src/internals.ts
packages/workflow/src/worker-interface.ts

Before this change, failure converters did not utilize custom payload converters unless explicitly instantiated with the a payload converter option. This behavior would be surprising in the common case of using the default failure converter.
While this technically is a breaking change, it is not marked as one since the `FailureConverter` API is considered experimental.

feat: Pass a PayloadConverter to FailureConverter methods

---

packages/worker/src/logger.ts

This will prevent jest from complaining about use of `console.error`.

chore: Use `process.stderr.write` for the default log function

---

CHANGELOG.md

The release will be made from the v1.4.4-release branch that points to `v1.4.3` + sdk-core commit that fixes the eager activity issue (see CHANGELOG).
I'll create another PR that will update core for the `main` branch to get some of the recent changes and this fix before we release `1.5.0`.

Update CHANGELOG for 1.4.4

---

package-lock.json
packages/client/package.json
packages/client/src/client.ts
packages/client/src/index.ts
packages/client/src/interceptors.ts
packages/client/src/schedule-client.ts
packages/client/src/schedule-helpers.ts
packages/client/src/schedule-types.ts
packages/client/src/workflow-client.ts
packages/client/src/workflow-options.ts
packages/common/src/time.ts
packages/common/src/type-helpers.ts
packages/test/src/test-schedules.ts

- Add Schedule API
- Add Schedule API

feat: Add Schedule API

---

packages/client/src/interceptors.ts
packages/client/src/workflow-client.ts
packages/interceptors-opentelemetry/src/client/index.ts
packages/interceptors-opentelemetry/src/index.ts
packages/test/src/test-interceptors.ts
packages/test/src/test-otel.ts

- In `WorkflowClientOptions`, interceptors should now be provided as an array of interceptor object, rather than an array of factory to those objects under a field named `calls`.
- Previous form is still allowed though deprecated
Before:
```
interceptors: {
calls: [
(workflowId) => {
create(...) => { ... }
}
]
}
```
Now:
```
interceptors: [
{
create(...) => { ... }
}
]
```
- The indirection was not useful and made interceptors looks complicated
- As discussed in https://github.com/temporalio/sdk-typescript/pull/937#discussion_r1010663304
- Updated tests
- Need to update doc and code samples

fix(client): Simplify WorkflowClient interceptors

---

.gitmodules

Git url is hard to make work in workflows ci

Use https submodule url for easier clones in CI

---

packages/client/src/schedule-helpers.ts

- Handle field `timezoneName` in schedule Proto to TypeScript decoding
- Missed that field in original PR

fix(client): Add missing field in schedules

---

packages/client/src/async-completion-client.ts
packages/client/src/base-client.ts
packages/client/src/client.ts
packages/client/src/interceptors.ts
packages/client/src/schedule-client.ts
packages/client/src/workflow-client.ts
packages/test/src/test-failure-converter.ts
packages/testing/src/index.ts

- Extracted a `BaseClient` super class over `Client`, `WorkflowClient`, `ScheduleClient` and `AsyncCompletionClient`.
- Improves maintainability

chore(client): Extract a BaseClient super class

---

.eslintrc
package-lock.json
packages/client/package.json
packages/client/src/iterators-utils.ts
packages/client/src/workflow-client.ts
packages/common/src/interfaces.ts
packages/test/src/integration-tests.ts
packages/test/src/test-failure-converter.ts
packages/test/src/test-iterators-utils.ts
packages/test/src/test-local-activities.ts
packages/test/src/test-replay.ts
packages/test/src/test-schedules.ts
packages/test/src/workflows/activity-failures.ts
packages/worker/src/index.ts
packages/worker/src/replay.ts
packages/worker/src/worker.ts

- In client package, introduce `WorkflowHandle.fetchHistory()` which returns the complete history for a workflow. That function might be useful in testing and replaces function `fetchWorkflowHistory`.
- The iterable returned by `WorkflowClient.list()` can now be easily transformed to an iterable of Workflow histories, using `WorkflowClient.list().intoHistories()`. Multiple Workflow histories are fetched in parallel (with a concurency of 5 by default).
- `WorkflowClient.list().intoHistories()` is now the proper way to provide histories to `Worker.runReplayHistories()` when those histories have to be fetched from an actual server. The previous experimental interface `ReplayExecutions` is no longer accepted.

chore: Refactor mass history replayer API (Part 1)

---

packages/core-bridge/index.d.ts
packages/core-bridge/src/conversions.rs
packages/worker/src/runtime.ts

- Make metrics export period for OTel configurable ([reference](https://github.com/temporalio/sdk-core/pull/442))

feat(worker): Make OTel export period configurable

---

.github/workflows/ci.yml
package.json
packages/core-bridge/package.json
packages/core-bridge/src/conversions.rs
packages/core-bridge/src/errors.rs
packages/core-bridge/src/helpers.rs
packages/core-bridge/src/runtime.rs
packages/core-bridge/src/testing.rs
packages/core-bridge/src/worker.rs

- `npm run format` now execute `cargo fmt` in the core-bridge package
- Similarly, `npm run lint` now execute `cargo cargo` in core-bridge
Rust code contained in package core-bridge but outside the core-sdk submodule can benefit from cargo fmt and cargo clippy, but it is easy to forget running them after modifying core-bridge's code.
Running these commands from that NPM package's format and lint scripts would help ensure that they are regularly run.
Fixes #970
Fixes #120

chore(core): Run clippy/fmt from npm's lint/format

---

.github/workflows/ci.yml
packages/core-bridge/Cargo.lock

- Updated SDK Core
- Fix heartbeats being counted as a logical WFT ([SDK Core 444](https://github.com/temporalio/sdk-core/commit/13bcad663568babbcea543833ddc7f3aacef7874))

fix(core): Fix heartbeats being counted as a logical WFT

---

package-lock.json
packages/create-project/package.json

If you have earlier versions of tar in your npm cache `npx @temporalio/create` will fail with node 18.
https://github.com/temporalio/temporal-learning/pull/39

chore(create-project): Depend on tar ^6.1.13

---

package-lock.json
package.json
packages/test/package.json
packages/test/src/helpers.ts
packages/test/src/integration-tests.ts
packages/test/src/test-async-completion.ts
packages/test/src/test-ephemeral-server.ts
packages/test/src/test-local-activities.ts
packages/test/src/test-replay.ts
packages/test/src/test-schedules.ts
packages/test/src/test-testenvironment.ts
packages/test/src/test-worker-activities.ts
packages/test/src/test-worker-lifecycle.ts
packages/test/src/test-workflow-cancellation.ts
packages/test/src/test-workflow-log-interceptor.ts
packages/test/src/test-workflows.ts

- Fix #988
- Did not upgraded to AVA 5.0 because that would reduce Node compatibility (>14.19, >16.15)

chore: Update AVA to 4.3

---

package-lock.json
packages/docs/docusaurus.config.js
packages/docs/package-lock.json
packages/docs/package.json
packages/docs/src/theme/DocBreadcrumbs/index.js

- Should considerably reduce the number of packages reported in #746
- It is known that certain transitive deps will still be reported, until some middle  package fix their own dependencies.

Update docusaurus and other deps with known vaulnerabilities

---

package-lock.json
packages/nyc-test-coverage/package.json
packages/nyc-test-coverage/src/index.ts
packages/nyc-test-coverage/src/loader.ts
packages/test/package.json
packages/test/src/test-nyc-coverage.ts

In @temporalio/nyc-test-coverage:
- Remove dependency on istanbul-instrumenter-loader
- Replaced by a private webpack module loader
- Add integration tests
- Modify rules to make sure that all user source files are included in coveerage
- 'istanbul-instrumenter-loader' was causing inclusion of vulnerable package ' loader-utils@1.4.0'
- project 'istanbul-instrumenter-loader' is no longer maintained (it has actually been archived)
- fix #994, fix #911, fix #872

fix: Get rid of istanbul-instrumenter-loader

---

package-lock.json
packages/client/package.json
packages/test/package.json
packages/testing/package.json

- Pinned package @grpc/grpc-js to ~1.7.3
- 1.8.3 cause a 10 second delay on node shutdown (fix #1023)
- 1.8.0 introduced an integrated retry mechanism which will duplicate our own, causing much more retries than expected
- I willimmediately open a distinct issue for updating to >1.8.x at a later time

fix: Pin version of @grpc/grpc-js

---

packages/test/src/integration-tests.ts
packages/test/src/test-sinks.ts
packages/test/src/test-workflows.ts
packages/test/src/workflows/return-search-attributes.ts
packages/worker/src/worker-options.ts
packages/worker/src/worker.ts
packages/workflow/src/interfaces.ts
packages/workflow/src/worker-interface.ts

- Can now start workers in debug mode by setting environment variable `TEMPORAL_DEBUG=true` (fix #1020)
- No longer warn about no activities when running a replay-only Worker (fix #890)
- Improved error message when requested workflow type is not an exported function (fix #375)
- `instanceof` on `WorkflowInfo` fields now works as expected (fix #659)
- Added `startTime` and `runStartTime` on `WorkflowInfo` (fix #1005, fix #694)

feat: Add startTime to WorkflowInfo, and more

---

packages/client/src/schedule-client.ts
packages/client/src/schedule-helpers.ts
packages/client/src/schedule-types.ts
packages/common/src/type-helpers.ts
packages/test/src/test-schedules.ts
packages/worker/src/worker-options.ts

- In `create` and `update` schedules, `spec` is still required, but can be empty. It is no longer required that the a schedule has at least one calandar, one interval or one cron spec.
- In `list`, all schedule properties (except `scheduleId`) are now optional, with a comment indicating that this structure is eventual consistent. This might change on server at some point in the future, but this matches the server behaviour for 1.18.x and 1.19.x.
- Duplicated fields from `ScheduleSummary` to `ScheduleDescription` to avoid further complexification of doc.
- Fix #1013
- Fix #967

fix(client): Schedules specs can be empty

---

packages/test/src/test-testenvironment.ts
packages/test/src/workflows/testenv-test-workflows.ts
packages/testing/src/index.ts

Tried to reproduce an issue reported in community slack and failed, might as well leave this test for reference.

test: Test ABANDONED child timer can be fast-forwarded

---

packages/common/src/converter/failure-converter.ts
packages/common/src/failure.ts
packages/test/src/test-failure-converter.ts

Test that failure details aren't leaked if chained from activity to workflow.
Also fix error message of `ActivityFailure`.

chore: Improve integration test for failure converter

---

packages/test/src/test-default-workflow.ts
packages/test/src/test-workflows.ts
packages/test/src/workflows/default-workflow-function.ts
packages/test/src/workflows/index.ts
packages/test/src/workflows/signals-ordering.ts
packages/worker/src/workflow/vm-shared.ts
packages/worker/src/workflow/vm.ts
packages/workflow/src/index.ts
packages/workflow/src/interfaces.ts
packages/workflow/src/internals.ts
packages/workflow/src/worker-interface.ts
packages/workflow/src/workflow.ts

- A workflow bundle can now do `export default async function (workflowType: string, ...args: unknown[]): Promise<unknown> { ... }` to define a default workflow handler.
- A workflow function can now do `setDefaultSignalHandler((signalName: string, ...args: unknown[]) => { ... })` to set a function that will handle signals sent for non-registered signal names.
- Partially covers #1015
- Resolves #973
- Resolves #846

feat(workflow): Add support for default workflow handler and default signal handler

---

packages/create-project/src/create-project.ts

Currently it's deleted after the init/commit step, so user starts out dirty:
```
$ git status
On branch main
Changes not staged for commit:
(use "git add/rm <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
deleted:    .post-create
```
`packages/create-project/cli.js`

fix: Remove `.post-create` before committing

---

packages/client/src/schedule-types.ts

- Modified schedule doc to not specify the exact number of most recent/future execution time.
- The numbers for listSchedules was incorrect (actual value is 5 rather than 10)
- Given that these numbers are tweakable at the server level, it seems more appropriate to consider the exact numbers as an implementation details rather than a contract.

doc(client): Dont specify exact count of prev/next schedules time

---

packages/client/src/workflow-options.ts
packages/common/src/interfaces.ts
packages/common/src/workflow-handle.ts
packages/test/src/test-interface-type-safety.ts
packages/workflow/src/workflow.ts

This PR makes two refinements to the `SignalDefinition` and `QueryDefinition` types:
1. `Args` and `Ret` types are branded into the resulting types, using virtual symbolic brands. This addresses #1051
2. The `name` field is allowed to be narrowed to sub-type of `string` via an optional generic which defaults to `string`. I've used the least-intrusive option available here, which leaves behavior completely unchanged for existing callers, at the expense of making strict names a bit more verbose. This addresses #1052 
Because #1051 and #1052 are making me sad.
1. Closes #1051 and #1052
2. How was this tested:  
3. We may want to update the [Workflow TS docs](https://github.com/temporalio/documentation/blob/40176f12b79a73cc23481a3effdd98ddc2289e5e/docs-src/typescript/workflows.md)

Stronger query and signal definitions

---

packages/client/src/connection.ts
packages/testing/src/connection.ts

It's an experimental API in Node.js and not available in Deno.

feat: Get rid of experimental AsyncLocalStorage.enterWith call

---

packages/create-project/src/helpers/install.ts

Ignore ENOENT errors from trying to edit `tsconfig.json` in sample root.
So tool doesn't crash in Node 17+.
1. Closes 
https://github.com/temporalio/samples-typescript/issues/251
`./cli.js --sample food-delivery`
Thanks @cliffordfajardo for reporting! 😊

fix(create-project): Support samples without tsconfigs

---

.github/workflows/ci.yml
packages/core-bridge/Cargo.lock
packages/core-bridge/src/conversions.rs
packages/core-bridge/src/runtime.rs
packages/core-bridge/ts/index.ts
packages/test/src/integration-tests.ts
packages/test/src/test-ephemeral-server.ts
packages/testing/src/index.ts

BREAKING CHANGE: the `TemporaliteConfig` interface was deleted but it likely was not directly referenced as only the deprecated `create` method accepted it.
Closes #1055

feat(testing): Use temporal CLI to power local test environment

---

packages/client/src/schedule-helpers.ts
packages/common/src/interfaces.ts
packages/common/src/workflow-options.ts
packages/test/src/test-schedules.ts
packages/workflow/src/workflow.ts

Before this change, TypeScript would have difficulties inferring the type for workflow options provided via the various SDK APIs when defined out of context.
For example, the following code would not compile:
```ts
const options = {
workflowId: uuid4(),
taskQueue: 'some-queue',
searchAttributes: { someIntAttr: [1] },
args: [3],
} as const;
const handle = await client.start(workflows.sleeper, options);
```
Note that args can only be inferred if the options are defined `as const` or the args are cast into a tuple (e.g. `args: [3] as [number]`).

Accept WorkflowOptions as const

---

CONTRIBUTING.md

Added a line to CONTRIBUTING.md mentioning to install protocal buffers after rust.
While following the contributing guide I got an error that protobuf wasn't installed on my MacBook during `npm ci` step.

docs: add install protocal buffers step to CONTRIBUTING.md doc

---

.github/workflows/ci.yml

Verified libc is low enough for us.
See also https://github.com/temporalio/sdk-typescript/pull/590

chore: Use Buildjet for ubuntu binary builds

---

packages/nyc-test-coverage/src/index.ts
packages/test/src/helpers.ts
packages/test/src/integration-tests.ts
packages/test/src/test-native-connection.ts
packages/test/src/test-nyc-coverage.ts
packages/test/src/test-schedules.ts
packages/testing/src/utils.ts
packages/workflow/src/workflow.ts
scripts/create-certs-dir.js
scripts/init-from-verdaccio.js
scripts/registry.js
scripts/utils.js
scripts/wait-on-temporal.mjs

- Multiple tests were design to check for file path, but assumed forward-slash as directory separator. These tests now correctly deal with Window's backward-slash file separator.
- Temporal CLI's dev server does not support arrays of ints or dates as Search Attribute values. Modify existing tests to not use such arrays. Note: the array syntax is still supported with ES visiblity and in Cloud.
- Temporal CLI's dev server does not support the "IN" operator in workflow in list workflow query. Silently ignore that failure if it happens.
- Some tests are expecting some specific error messages, that differs on Windows or with the Temporal CLI's dev server. Modified these checks to include the missing variants.
- Some utility scripts used in CI tests were expecting a Unix-style filesystem (ie. …

fix: Fix multiple tests on Windows and/or Temporal CLI dev server

---

package-lock.json
packages/common/src/proto-utils.ts
packages/test/src/test-proto-utils.ts

- `fromProto3JSON` doesn't allow `null` values on 'bytes' fields. This turns out to be a problem for payloads. This fix this situation by recursively descending on events and fixing payloads that have null data field

fix: Fix `null` payload data in `historyFromJSON`

---

packages/test/src/test-workflows.ts
packages/worker/src/logger.ts
packages/worker/src/worker-options.ts
packages/worker/src/workflow-log-interceptor.ts
packages/worker/src/workflow/reusable-vm.ts
packages/worker/src/workflow/vm.ts
packages/workflow/src/interfaces.ts
packages/workflow/src/internals.ts
packages/workflow/src/worker-interface.ts
packages/workflow/src/workflow.ts

- [Lazily initialize the default sinks logger](https://github.com/temporalio/sdk-typescript/commit/540896e03e9e0d1564c3d2198a1bc7c57d5b1795)
- [Export `log` from workflow](https://github.com/temporalio/sdk-typescript/commit/5a2789661bc4afa2c66056b4307d14f48146a0d4) - a logger that funnels messages to the default worker logger sink.
```ts
import * as workflow from '@temporalio/workflow';
export async function myWorkflow(): Promise<void> {
workflow.log.info('hello from my workflow', { key: 'value' });
}
```

feat: Workflow logger improvements

---

packages/workflow/src/workflow.ts

Use [structuredClone](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) to clone sink call arguments at call time.
While this adds some runtime overhead, it leads to a more predictable experience when an argument is mutated after being passed to a sink as well as better exceptions when passing a non-transferrable object to a sink.
Only available from Node.js >= 17.

feat(workflow): Clone sink args at call time

---

packages/client/src/schedule-client.ts
packages/client/src/schedule-helpers.ts

Fix incorrect schedule spec boundaries validation on hour and day-of-month fields
- Fixes #1105
- Thanks to @florianmorath for reporting

fix(client): Fix incorrect schedule spec boundaries

---

packages/testing/src/index.ts

To allow accessing the operator service without the need to cast to `Connection`.

fix: Use Connection class for test env connection property

---

packages/client/src/schedule-client.ts
packages/client/src/schedule-helpers.ts
packages/client/src/workflow-client.ts
packages/common/src/workflow-options.ts
packages/create-project/src/helpers/install.ts
packages/proto/scripts/compile-proto.js
packages/test/scripts/compile-proto.js
packages/workflow/src/workflow.ts

- Better error message when `executeWorkflow()` and similar are given a workflowFunction fucntion that is anonymous (fix #367)
- Better error message when Workflow-only APIs are called from non-Workflow execution context (fix #553)
- On `create`, do not use `@tsconfig/node20` because it is broken (fix #1125)
- Include proto comments in API files generated by protobufjs (fix #506)
- Minor refactor of schedule's error handling

fix: Better error messages, and more

---

package-lock.json
packages/worker/package.json

- Updated unionfs (jump over release 4.5.0, which is broken) - Fix #1131

chore: Update unionfs (avoid broken release)

---

package-lock.json
packages/activity/src/index.ts
packages/client/src/connection.ts
packages/client/src/schedule-types.ts
packages/common/package.json
packages/common/src/activity-options.ts
packages/common/src/deprecated-time.ts
packages/common/src/index.ts
packages/common/src/retry-policy.ts
packages/common/src/time.ts
packages/common/src/workflow-options.ts
packages/core-bridge/ts/index.ts
packages/test/src/integration-tests.ts
packages/test/src/load/all-scenarios.ts
packages/testing/package.json
packages/testing/src/index.ts
packages/worker/package.json
packages/worker/src/worker-options.ts
packages/workflow/src/cancellation-scope.ts
packages/workflow/src/interfaces.ts
packages/workflow/src/workflow.ts

- Added type definitions for "ms-formated strings"
- Introduced a Duration type which is either a ms-formated string or a number of milliseconds
- Make ms-formated-string to number conversions throw on invalid time specifications
- Invalid time specifiers would previously cause misterious issues: including unhandled commands (ie. `sleep('1 month')`) or `condition` behaving as if no timeout was provided (ie. `condition(fn, '1 month')`)
- Fix #1046 and #1066

feat!: Protect against ms durations errors

---

packages/activity/src/index.ts
packages/client/src/async-completion-client.ts
packages/common/src/converter/failure-converter.ts
packages/common/src/errors.ts
packages/common/src/failure.ts
packages/core-bridge/ts/errors.ts
packages/interceptors-opentelemetry/src/workflow/index.ts
packages/worker/src/activity-log-interceptor.ts
packages/worker/src/activity.ts
packages/worker/src/runtime.ts
packages/worker/src/worker.ts
packages/worker/src/workflow-log-interceptor.ts
packages/workflow/src/errors.ts
packages/workflow/src/interfaces.ts
packages/workflow/src/internals.ts

The number one reported issue stems from instanceof checks and SDK module level variables, which fail when there are multiple versions of the SDK packages installed.
- Remove the instanceof checks in favor of coded `is` methods on the critical classes.
- Install the activity context local storage globally.
Note that the `is` methods do no use the class name, which may be lost when using minifiers.

fix: Remove most instanceof checks from SDK

---

.github/workflows/ci.yml

For security concerns, could be a vector for shell injection.
Not a huge concern but also better removed than not.

chore: Remove CI step to print build information

---

package-lock.json
packages/core-bridge/src/conversions.rs
packages/core-bridge/src/runtime.rs
packages/core-bridge/ts/index.ts
packages/test/src/load/args.ts
packages/test/src/load/setup.ts
packages/test/src/load/starter.ts
packages/test/src/load/worker.ts
packages/test/src/test-sinks.ts
packages/test/src/test-workflow-log-interceptor.ts
packages/test/src/workflows/log-sink-tester.ts
packages/testing/src/utils.ts
packages/worker/src/runtime.ts
packages/worker/src/utils.ts
packages/worker/src/worker-options.ts
packages/worker/src/workflow/threaded-vm.ts
packages/workflow/src/worker-interface.ts
scripts/wait-on-temporal.mjs

- Added `WorkerOptions` properties `maxConcurrentWorkflowTaskPolls` and `maxConcurrentActivityTaskPolls`, which allow controlling the number of pollers to be used to fetch Workflow/Activity tasks from the  Task Queue. Properly adjusting these values should allow better filling of the corresponding execution slots.
- Remove the `@experimental` tag on `reuseV8Context`
- Better auto-configuration of `maxCachedWorkflows`, including using a different formula when `reuseV8Context` is enabled (fix #838)
- Default value for `maxConcurrentWorkflowTaskExecutions` has been reduced to 40 (was previously 100), as higher values increase the risk of Workflow Task Timeouts unless other options are also tuned. This was not problem previously because the single poller was unlikely to fill in all execution …

feat(worker): Add support for concurrent pollers

---

packages/client/src/async-completion-client.ts
packages/client/src/connection.ts
packages/client/src/errors.ts
packages/client/src/helpers.ts
packages/client/src/schedule-client.ts
packages/client/src/workflow-client.ts
packages/common/src/converter/payload-converter.ts
packages/common/src/errors.ts
packages/proto/scripts/compile-proto.js
packages/test/src/integration-tests.ts
packages/test/src/load/starter.ts
packages/test/src/test-async-completion.ts
packages/test/src/test-client-errors.ts
packages/test/src/test-payload-converter.ts
packages/worker/src/runtime.ts
packages/worker/src/worker.ts

- All Client APIs now throw `NamespaceNotFoundError` when appropriate, rather than `WorkflowNotFound`, `ScheduleNotFound` or `ActivityNotFound` (fix #1145, fix #976)
- Errors that happen while preparing API requests from a `Client`, and particularly errors happening while converting input objects to payloads, now results in throwing an appropriate exception, rather than an opaque ServiceError.

feat(client): Throw more specific errors from Client APIs

---

packages/common/src/converter/payload-converter.ts
packages/test/src/test-local-activities.ts
packages/test/src/test-workflows.ts
packages/worker/src/runtime.ts
packages/worker/src/worker.ts
packages/worker/src/workflow/reusable-vm.ts
packages/worker/src/workflow/threaded-vm.ts
packages/worker/src/workflow/vm.ts
packages/worker/src/workflow/workflow-worker-thread.ts
packages/worker/src/workflow/workflow-worker-thread/input.ts
packages/workflow/src/interfaces.ts
packages/workflow/src/internals.ts
packages/workflow/src/workflow.ts

Previously the worker would needlessly retry these local activities.
With this change, the worker fails the workflow task allowing a user to deploy a fix.
Replaces https://github.com/temporalio/sdk-typescript/pull/1150 with better behavior.
Matches Java behavior https://github.com/temporalio/sdk-java/pull/1628.

fix: Fail workflow task if local activity not registered with worker

---

CHANGELOG.md
packages/activity/src/index.ts
packages/client/src/task-queue-client.ts
packages/core-bridge/src/conversions.rs
packages/core-bridge/ts/index.ts
packages/test/src/test-activity-log-interceptor.ts
packages/test/src/test-ephemeral-server.ts
packages/test/src/test-isolation.ts
packages/test/src/test-worker-versioning.ts
packages/worker/src/activity-log-interceptor.ts
packages/worker/src/worker-options.ts

- Updated CHANGELOG.md file in prep for 1.8.0.
- [Update core to get local activity start-to-close fix](https://github.com/temporalio/sdk-typescript/pull/1148/commits/e920da3263e7f2248738d533ae27b6c41eb6d8ad)
- [Fix flake in test-isolation](https://github.com/temporalio/sdk-typescript/pull/1148/commits/7153d4dc4449ed59d2859a81dd9cc8ca66b304c9)
- [Rename activity context logger to log, moar changelog edits](https://github.com/temporalio/sdk-typescript/pull/1148/commits/8379ca42ab60a09d251242393d1515cb142bb740)
- [Add versioning changelog and minor API changes](https://github.com/temporalio/sdk-typescript/pull/1148/commits/7999b73536d168e4e5f8caed82768afe2a7693a7)

chore: Update CHANGELOG.md file in prep for 1.8.0 and make last minute API changes

---

CHANGELOG.md

Breaks workers deployed on lower versions (eg 14.17 is default version on Render)

docs: Add boom to Node version support change

---

packages/worker/src/index.ts
packages/worker/src/workflow-log-interceptor.ts
packages/workflow/src/interceptors.ts
packages/workflow/src/internals.ts
packages/workflow/src/sinks.ts
packages/workflow/src/workflow.ts

- [Make log attributes optional for defaultWorkerLogger sink](https://github.com/temporalio/sdk-typescript/commit/8d3a3f1770a0962b9f92367f31795d6ce9f66994)
- [Attach log attributes to every workflow log message](https://github.com/temporalio/sdk-typescript/commit/5938b701526a0dc4f199e8cef037250b3177888f)
The approach taken in this PR (compared to the alternative #1158) attaches the log attributes in workflow context where the user has more control.

feat(workflow): Logger improvements

---

packages/activity/src/index.ts
packages/common/src/failure.ts
packages/core-bridge/ts/errors.ts
packages/workflow/src/interfaces.ts

This doesn't work when errors are passed from different v8 contexts.
Only known to affect ShutdownError with jest (see https://github.com/jestjs/jest/issues/2549).

fix: Remove instanceof Error checks from `is` methods

---

packages/workflow/src/workflow.ts

An argument name in a function type signature.
The semantics implied by the name were incorrect. 
`npm run test`
4. Any docs updates needed?
I believe that the API reference docs at https://typescript.temporal.io/api/namespaces/workflow#executechild will update automatically although I haven't researched exactly how that happens.
I believe that this change should not have any backwards compatibility problems, although it is technically possible that something could be introspecting on the argument name.

Fix argument name in executeChild signature

---

.gitignore
packages/test/src/integration-tests.ts
packages/test/src/workflows/index.ts
packages/test/src/workflows/url-whatwg.ts
packages/worker/src/workflow/bundler.ts
packages/worker/src/workflow/module-overrides/url.ts
packages/worker/src/workflow/reusable-vm.ts
packages/worker/src/workflow/vm.ts

Enable access to URL and URLSearchParams inside the workflow sandbox either using globals or with
an import of the 'url' module.
See #981 
1. Closes 
#981 
Added a system test case

Add support for URL/URLSearchParams inside the workflow sandbox

---

packages/activity/src/index.ts
packages/client/src/async-completion-client.ts
packages/client/src/errors.ts
packages/client/src/iterators-utils.ts
packages/client/src/schedule-client.ts
packages/client/src/task-queue-client.ts
packages/client/src/workflow-client.ts
packages/common/src/converter/failure-converter.ts
packages/common/src/converter/payload-converter.ts
packages/common/src/errors.ts
packages/common/src/failure.ts
packages/common/src/type-helpers.ts
packages/core-bridge/ts/errors.ts
packages/interceptors-opentelemetry/src/workflow/index.ts
packages/test/src/integration-tests.ts
packages/test/src/test-type-helpers.ts
packages/test/src/test-workflow-unhandled-rejection-crash.ts
packages/worker/src/activity-log-interceptor.ts
packages/worker/src/activity.ts
packages/worker/src/errors.ts
packages/worker/src/replay.ts
packages/worker/src/worker.ts
packages/worker/src/workflow-log-interceptor.ts
packages/workflow/src/errors.ts
packages/workflow/src/interfaces.ts
packages/workflow/src/internals.ts
tsconfig.base.json
tsconfig.prune.json

#1128 introduced a new strategy, based on presence of a symbol, for checking `instanceof` on Error classes defined by SDK. However this turned out to work incorrectly when running in Jest, because of the remaining `instanceof Error` check. #1162 tried to fix that one, but missed the particular case of converting errors thrown from Core.
- Introduce a new decorator function `SymbolBasedInstanceOfError` that adds a custom `instanceof` handler to error classes. It does so by defining a `[Symbol.hasInstance]` function on the object constructor. That custom `instanceof` handler look for the presence of a specific symbol.
- Replace the recently introduced `.is(...)` function by the `.[Symbol.hasInstance]()` function, which makes it automatically used by the `instanceof` operator, in place of …

Use custom symbol-based impl of `instanceof`

---

packages/activity/src/index.ts
packages/testing/src/index.ts
packages/worker/src/worker.ts

- Correctly set `heartbeatTimeoutMs` on `Context.current().info` (fix #1182)
- Also expose `currentAttemptScheduledTimestampMs`

fix(activity): Add missing Activity Info fields

---

packages/worker/src/workflow/bundler.ts

Allow the bundler to understand `.js` imports in `.ts` executed with `tsx`, `jiti`, `ts-node` and similar Deno-like runtimes for node
Fix copied from https://github.com/softwareventures/resolve-typescript-plugin#obsolete
1. Closes #1185 
2. How was this tested: works on my machine :tm:

fix(worker): allow bundling typescript with .js extensions

---

packages/common/src/workflow-options.ts

According to Maxim, this was changed from
`WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE_FAILED_ONLY` to `WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE` when forked from Cadence.
@cretz and I have also verified from other sources:
Go:
https://github.com/temporalio/sdk-go/blob/master/client/client.go#L281
Java:
https://github.com/temporalio/sdk-java/blob/master/temporal-sdk/src/main/java/io/temporal/client/WorkflowOptions.java#L146
.NET:
https://dotnet.temporal.io/api/Temporalio.Client.WorkflowOptions.html#Temporalio_Client_WorkflowOptions_IdReusePolicy
Python:
https://python.temporal.io/temporalio.client.Client.html#start_workflow
Server:
https://github.com/temporalio/temporal/blob/main/service/frontend/workflow_handler.go#L2004
https://github.com/temporalio/temporal/blob/main/common/enums/defaults. …

fix(doc): Rectify the default workflowIdReusePolicy

---

packages/common/src/index.ts
packages/common/src/versioning-intent-enum.ts
packages/workflow/src/workflow.ts

The import was added between 1.8.0 and 1.8.1.
Reduces the SDK test workflow bundle from 2.55MB to 1.04MB.

fix: Remove accidental import of large protos into workflow library

---

packages/client/src/workflow-client.ts
packages/test/src/integration-tests.ts

Throw `WorkflowExecutionAlreadyStartedError` in `signalWithStart()` just like `start()`.
So that the both functions have consistent errors in this case.
1. Closes
N/A
3. How was this tested:
Unit tests
4. Any docs updates needed?
No

Throw WorkflowExecutionAlreadyStartedError on signalWithStart

---

packages/common/src/converter/payload-converter.ts
packages/create-project/src/helpers/install.ts
packages/test/src/test-payload-converter.ts

- Use `for … of` loop instead of `for … in` for iterating on array in payload converter.
- This avoids issues when enumerable properties have been added on `Array.prototype` (eg. some badly implemented polyfills; they should be using `Object.defineProperty(..., { enumerable: false })` instead).

fix: Use `for … of` loop instead of `for … in`

---

packages/test/src/test-sinks.ts
packages/test/src/workflows/core-issue-589.ts
packages/test/src/workflows/index.ts

- Updated core-sdk to include temporalio/sdk-core#597
- Added TS test for that issue
- This could notably cause situations where calls to sink functions not configured with `calledDuringReplay = true` would not be relayed, as well as situations where `patched(...)` would return false even though this part of the code was being executed for the first time.

fix(workflow): Fix isReplaying being incorrectly true due to query

---

package-lock.json
package.json
packages/client/package.json
packages/common/package.json
packages/proto/package.json
packages/test/package.json

upgraded to latest protobuf-related dependencies
Trying to help with #1219 
1. Closes #1219
```
npm ci
npm test
```
Nope

Upgrade protobuf dependencies (#1219)

---

packages/test/src/test-signal-query-patch.ts
packages/test/src/test-sinks.ts
packages/test/src/workflows/signal-query-patch-post-patch.ts
packages/test/src/workflows/signal-query-patch-pre-patch.ts
packages/workflow/src/workflow.ts

- Fix a case where `isReplaying` is incorrectly `true` if a workflow receives a signal, then the workflow is evicted from cache (or worker is restarted), then a query is sent to that workflow. This may have caused `patched()` to succeed despite that patch not having been set on first execution, and NDE afterward when the workflow get replayed.
- Fix a flake in CI test

fix(workflow): Fix isReplaying incorrectly true in signal-evict-query scenario

---

packages/client/src/client.ts
packages/client/src/interceptors.ts
packages/client/src/schedule-client.ts
packages/client/src/schedule-types.ts
packages/common/src/converter/data-converter.ts
packages/common/src/converter/failure-converter.ts
packages/worker/src/replay.ts
packages/worker/src/worker.ts
packages/workflow/src/interceptors.ts
packages/workflow/src/workflow.ts

The following APIs are no longer marked as experimental:
- Schedules
- Failure Converters
- Local Activities
- Replay Histories
For info, at this date, the following APIs are still marked as experimental:
- Versioning / TaskQueueClient (newly introduced)
- Client's gRPC retry options (not sure we want to commit to long time support on this, and for sure, not before we upgrade to grpc-js 1.8)
- All telemetry options (likely to change due to upcoming advanced metrics support)
This one is deemed to perpertual 'experimental'
- Workflow Internal Interceptors (this is for advanced use cases, and we don't want to commit to long term support)

chore: Remove experimental flags on Schedules, Failure Converters, Local Activities and Replay Histories

---

.github/workflows/stress.yml

- Make it possible to manually start CI stress tests

chore: Allow manually starting stress tests in CI

---

packages/activity/src/index.ts

Added missing bindings on activity context class.
Since we are restoring the `Context` class from `AsyncLocalStorage`. Class scope is missing and thus rebinding is necessary. Attempting to use `Context.current().heartbeat()` or `Context.current().sleep()` would result on `this` property is undefined error.
1. Closes 
I tested it with the `activities-cancellation-heartbeating` SDK example.
Since it addresses a current bug, no doc changes are necessary.

fix(activity): Change to arrow function notation so class context is not lost

---

packages/worker/src/worker-options.ts

So they know to do so. Without doing so, they may not realize why their Workers aren't picking up tasks.
Could put note under `useVersioning` instead, but imagine `buildId` is more often looked at.

docs: Tell versioning users to call updateBuildIdCompatibility

---

packages/test/src/test-testenvironment.ts
packages/test/src/workflows/testenv-test-workflows.ts
packages/worker/src/worker.ts

- Slightly modify the `raceActivityAndTimer` test so that we wait for activity completion before actually completing the workflow. This avoid bug described in https://github.com/temporalio/sdk-java/issues/1138. The previous workaround was failing on Windows and causing some rare CI flakes.

fix: Fix race in TestEnvironment test causing flakes

---

packages/worker/src/runtime.ts

- Match Python and .NET SDKs.
- Reduce noise.

feat: Reduce the default Core log level to WARN and non Core Rust logs to ERROR

---

packages/client/src/connection.ts

- Minor doc change to make it clear that the Operator Service API is incompatible with Temporal Cloud.

doc(client): Document that OperatorService is incompatible with Cloud

---

packages/activity/src/index.ts
packages/client/src/base-client.ts
packages/client/src/connection.ts
packages/client/src/types.ts
packages/test/src/test-client-connection.ts

Clients and the Connection class get a `withAbortSignal` context manager that can be used to cancel all ongoing connections started within a function's scope.
```ts
const ctrl = new AbortController();
setTimeout(() => ctrl.abort(), 10_000);
// 👇 throws if incomplete by the timeout.
await conn.withAbortSignal(ctrl.signal, () => { /* make client or direct grpc calls */);
```
Provide a way to abort client grpc calls.

feat(client): Add `withAbortSignal` context manager

---

package-lock.json
packages/test/src/test-sinks.ts
packages/test/src/test-workflow-log-interceptor.ts
packages/test/src/test-workflows.ts
packages/test/src/workflows/internals-interceptor-example.ts
packages/test/src/workflows/log-sink-tester.ts
packages/worker/src/index.ts
packages/worker/src/worker-options.ts
packages/worker/src/worker.ts
packages/worker/src/workflow/interface.ts
packages/worker/src/workflow/logger.ts
packages/worker/src/workflow/threaded-vm.ts
packages/worker/src/workflow/vm-shared.ts
packages/worker/src/workflow/workflow-worker-thread/output.ts
packages/workflow/src/index.ts
packages/workflow/src/internals.ts
packages/workflow/src/logs.ts
packages/workflow/src/sinks.ts
packages/workflow/src/worker-interface.ts
packages/workflow/src/workflow.ts

- Deprecate `defaultSink()` and `LoggerSinks`. SDK's logger sink is now forcibly injected. Registering a custom logger sink named `defaultWorkerLogger` is still supported, but discouraged and deprecated.
- Refactored sink code internally.
- These changes adds up to better DX, notably by:
- Promoting clear usage patterns regarding Workflow logging that works out-of-the-box;
- Discourage the use of insufficiently documented features (eg. possibility of redirecting workflow logs by registering a custom `defaultWorkerLogger` sink);
- Remove the requirement that users should call `defaultSinks()` if they were to add custom sinks, which was error prone and a recurring source of support question.
- Prepare the code base for other, similar upcoming refactors and some features (eg. custom metrics, …

chore: Deprecate `defaultSinks`

---

packages/common/src/internal-non-workflow/tls-config.ts

Change serverNameOverride to not be testing only
Using serverNameOverride is a legitimate use case in production cases
1. Closes 

docs: Change serverNameOverride to not be testing only

---

packages/common/src/converter/protobuf-payload-converters.ts
packages/proto/src/patch-protobuf-root.ts
packages/test/src/test-patch-root.ts

- In a few places, we reflectively visit and transform our protobuf definitions. To determine the type of node being visited (Root, Namespace or Type), we would previously check the object's `constructor.name`. However, that name could get mangled if the package was bundled and minimized, which would generally result in error messages such as:
```
<app-dir>/node_modules/@temporalio/client/src/types.ts:62
export const { WorkflowService } = proto.temporal.api.workflowservice.v1;
^
TypeError: Cannot read properties of undefined (reading 'api')
```
We now check `constructor.className` instead, which is a convenient property added by the protobufjs library, specifically for the purpose of reflection.
- We provide no guarantee regarding the inclusion of `@temporalio/*` packages as part of …

fix(proto): protobuf exports may be incorrect if minimized

---

packages/core-bridge/Cargo.lock
packages/core-bridge/src/conversions.rs
packages/core-bridge/src/runtime.rs
packages/test/src/load/worker.ts
packages/test/src/test-otel.ts

- Recently, TS SDK had been built over a custom branch of Core SDK, intentionally ignoring changes that affected Core telemetry support. This PR reconnects to the main branch of Core SDK (though not the latest commit), notably bring in the following PR:
- temporalio/sdk-core#584
- temporalio/sdk-core#544
- temporalio/sdk-core#592
- temporalio/sdk-core#596
- temporalio/sdk-core#599
- temporalio/sdk-core#602
- temporalio/sdk-core#609
- temporalio/sdk-core#608
- temporalio/sdk-core#611
Note that this PR adds no new feature by itself.

chore: Update SDK Core to 617612aa

---

packages/test/src/helpers-integration.ts
packages/test/src/integration-tests-old.ts
packages/test/src/test-integration-codec-old.ts
packages/test/src/test-integration-old.ts
packages/test/src/test-integration-workflows.ts

There was a mistake in https://github.com/temporalio/sdk-typescript/pull/1299: tests inside the `integration-tests` subdirectory were not being run.
But that mistake emphasizes that it's not really desirable to have the nested directory. So instead of modifying the `test` and `test.watch` command definitions in `package.json`, this PR flattens the directory structure as follows
```
helpers.ts
helpers-integration.ts     // helper boilerplate shared by the new-style integration tests 
test-integration-*.ts      // i.e. new style integration tests (i.e. not matching -old-*.ts)
test-integration-old-*.ts  // old-style integration tests
```

Flatten test directory structure

---

packages/test/src/helpers.ts
packages/test/src/load/worker.ts
packages/test/src/test-isolation.ts
packages/worker/src/worker-options.ts
packages/worker/src/worker.ts

- `WorkerOptions.reuseV8Context` is now enabled by default. It may be opted out by explicitly setting that option to false.
- The Reuse V8 Context execution model brings significant performance improvements.
- The Reuse V8 Context execution model has been very stable since it was first introduced, with no issue being reported despite having been enabled in production by most of our largest TS SDK users for months.

feat(worker): Enable reuseV8Context by default

---

packages/worker/src/worker-options.ts
packages/worker/src/worker.ts

- Rewrite doc comment on `WorkerOptions.reuseV8Context` to not make it deprecated, but only that it is strongly recommended not to disable that option.

fix(worker): Dont deprecate non-reuseV8Context yet

---

packages/client/src/workflow-client.ts
packages/test/src/test-integration-update.ts

This PR fixes a mistake in the recently-introduced update `workflowHandle.getUpdateHandle(...)` API https://github.com/temporalio/sdk-typescript/pull/1312.  It should not take `workflowId` as an argument since the appropriate `workflowId` is the one on the `workflowHandle`.

Fix getUpdateHandle API

---

packages/worker/src/worker-options.ts

It's not obvious that this is required, hopefully this comment will help steer users in the right path.

docs: Add note on custom conveters and bundleWorkflowCode

---

packages/docs/docusaurus.config.js
packages/docs/sidebars.js

Fixed multiple issues with published API docs:
- Using snipsync comment tags to import content from an `@example` TS Doc section results in an invalid markdown code block (fix #1339)
- Items in the sidebar are sorted in reverse-alphabetical order (see image)
- In sidebar, namespaces entries appears twice: once as the category, and another as the first entry in that list (see image)

doc: fix sort order + snipsync examples issue

---

packages/worker/src/workflow/bundler.ts

Outdated link to docs in the bundler script when there is a Webpack error
To link users to the right documentation page.

Update webpack error doc link in worker/bundler.ts

---

packages/core-bridge/src/conversions.rs
packages/core-bridge/src/runtime.rs
packages/test/src/helpers.ts
packages/test/src/test-otel.ts
packages/test/src/test-prometheus.ts
packages/test/src/test-runtime.ts
packages/worker/src/runtime.ts
packages/worker/src/worker.ts

- Fix `Runtime.install()` failing with error `Failed to build otlp exporter options: UninitializedField("headers")` when configuring OTEL metric exporter is configured without specifying headers (fix #1342).
- Fix Rust panic + TS hanging when trying to create a Worker if `Runtime` has been configured with Prometheus metrics exporter, but the specified port is already taken.
- Add more TS side tests related to Prometheus and OTEL metric exports.
- Also fix incorrect reporting `Ignoring WorkerOptions.interceptors.workflowModules because WorkerOptions.workflowBundle is set. To use workflow interceptors with a workflowBundle, pass them in the call to bundleWorkflowCode.`

fix(worker): Fix prometheus and otel regressions

---

packages/meta/src/index.ts
scripts/prepublish.mjs

- Change the order in which packages are visited by the TypeDoc exporter.
- When types are reexported, TypeDoc canonicalize references to that type to the first public export it encountered. Given the previous package ordering, that means that, for example, ` ApplicationFailure` would appear under the `activity` package, rather than the `common` package.
- Updated our prepublish script to also update `devDependecies` and `peerDependencies`.
- Some users have faced issues with this using the 1.9.0 release. 1.9.1 fixed the invalid dependencies, but the change to the script had not been comited.

doc: Avoid doctype reexports canonicalization issue

---

packages/test/src/test-isolation.ts

I noticed we were missing this coverage so I added it.
See https://github.com/temporalio/sdk-typescript/issues/1355 for more details.

chore: Add test for module property mutation isolation

---

packages/core-bridge/Cargo.lock

- Updated Core SDK to [520040](https://github.com/temporalio/sdk-core/commit/520040aba1b044dd2d120cb75ce303fca4d81091).
- Fix deprecated patch removal when no subequent command (temporalio/sdk-core#671).
- Fix incorrect ordering of a query execution that could happen if new workflow tasks came in while theere were buffered queries (temporalio/sdk-core#673).
- Fix a possibility of sending local activity marker after the Workflow Task Complete command  (temporalio/sdk-core#678).
- Wait for activity completes to reach server before shutdown (temporalio/sdk-core#681).
- Update protobuf definitions to work with the new `EVENT_TYPE_WORKFLOW_EXECUTION_UPDATE_REQUESTED` event (temporalio/sdk-core#677).

core: Update SDK to 520040

---

packages/client/src/grpc-retry.ts

* Raise initial interval to 100ms (from 20ms)
* Drop max interval to 5s (from 10s)
* Drop backoff factor to 1.7 (from 2.0)
* Raise jitter factor to 0.2 (from 0.1)
The current retry options for the TypeScript SDK are a little wonky, as the existing initial interval is *by far* the most aggressive among all Temporal SDKs.  This brings the default parameters in line with the changes already made to the Java SDK and in flight for the Core SDK.
This also fixes a wart: the TypeScript SDK can exhaust all retries in 9.200 seconds, if the random jitters for each retry align in just the right way, and we want all SDKs to keep retrying for at least 10 seconds after the initial failure.
This advances progress on https://github.com/temporalio/features/issues/27 (aka SDK-118 in internal Jira).

Bring gRPC retry options in line with other SDKs.

---

packages/worker/src/worker.ts

Unreference timer created in `parseWorkflowCode` which can prevent Node.js from closing the event loop until the timer has fired.
The `parseWorkflowCode` function creates a 10 second timeout to keep the script and context from getting garbage collected. For normal usage that timeout is not a problem, since workers are expected to run for longer than 10 seconds anyway.
However, when running unit tests these timers can keep the Node.js event loop from shutting down even after the tests have completed successfully, if the tests complete in less than 10 seconds. That's especially common when running individual tests cases rather than the entire test suite.
The fix is rather simple. We just need to "[unreference](https://nodejs.org/api/timers.html#timeoutunref)" the timer, to prevent it from …

Unreference timer created in parseWorkflowCode

---

packages/common/src/internal-non-workflow/data-converter-helpers.ts
packages/test/src/payload-converters/failure-converter-bad-export.ts
packages/test/src/test-custom-payload-converter.ts

FailureConverters were reusing the error messages of PayloadConverters, creating confusion.
1. Closes 
#1369 
Added two unit tests

fix(common): Improve error messages for failureConverters (#1369)

---

packages/worker/src/worker-options.ts

Fix a typo in comment.
So it's consistent with the actual code.
1. Closes 

Fix comment typo on how default maxConcurrentActivityTaskPolls is calculated

---

packages/client/src/workflow-options.ts

Removed experimental tag from Start Delay option
To indicate the current state of Start Delay

Remove experimental from startdelay in workflow-options.ts

---

packages/core-bridge/Cargo.lock
packages/core-bridge/Cargo.toml
packages/core-bridge/src/conversions.rs
packages/core-bridge/src/runtime.rs
packages/core-bridge/ts/index.ts
packages/test/src/test-native-connection-headers.ts
packages/test/src/test-prometheus.ts
packages/worker/src/runtime.ts

Added new metrics options
Also autoformatted a bunch of stuff. Feel free to exclude that commit.
Expose Core features
1. Closes https://github.com/temporalio/sdk-typescript/issues/1380
Added tests. Unfortunately testing the specifics of the OTel metrics is not really reasonable, but, the option is passed through in the same way as Prom, which is.

Update Core & pass through new metrics options

---

package-lock.json
packages/docs/package-lock.json

- Updated Core SDK:
- Evictions in their own activations (temporalio/sdk-core#712)
- Fixed some npm deps with CVE

chore: Update dependencies

---

package-lock.json
packages/client/package.json
packages/test/package.json
packages/test/src/test-client-connection.ts
packages/test/src/test-native-connection-headers.ts
packages/testing/package.json
packages/testing/src/connection.ts

- Remove version pin on `@grpc/grpc-js`, and update it to 1.10.6.
- Added tests to assert that bugs and concerns regarding grpc-js 1.8+ are no longer pertinent.
grpc-js had been pinned to 1.7.3 in #1073, as 1.8.x introduced multiple bugs, as well a built-in retry feature, which could possibly conflict with our own retry interceptor.
Recently, there's been security concerns regarding older releases of grpc-js, as well as report of a bug that has been presumably been resolved in recent grpc-js releases.
After more testing, it has been demonstrated that the built-in retry mechanism introduced in grpc-js 1.8 does not conflict with ours. Their retry mechanism is enabled by default, but will only perform so called "transparent retries" unless configured otherwise.
Transparent retries are cases …

Update grpc-js to 1.10.x

---

package-lock.json
package.json
packages/worker/package.json
packages/worker/src/logger.ts
packages/worker/src/workflow/bundler.ts

- Don't include color control characters when logging bundler output.
- Log bundler multi-line output as a single log record.
Since we take this output and give it to a logging mechanism:
- Color should be omitted since the log message might not be written to a color-enabled console or encapsulated in JSON thus turning the control characters into a nuisance for reading.
- Multi-line message should be logged as a single record to maintain context.
1. Closes: n/a
2. How was this tested: Locally.
3. Any docs updates needed? None.

fix(bundler): Pass Webpack output to logger in a single record

---

.github/workflows/ci.yml
packages/core-bridge/scripts/build.js

- In CI, build native artifacts for Linux targets in Docker containers, using the `manylinux-2.24` image; this effectively brings the required glibc version down to 2.18 (we're technically building against glibc 2.24, but it appears that the resulting library file is only binding to 2.18 and older symbols).
- In the recent CI refactor, we stopped using Buildjet's Ubuntu 18.04 runners, as they are incompatible with some recent and upcoming GHA changes. This resulted in increasing the required glibc version from 2.17 (in 1.9) to 2.29 (in 1.10 on x64) and 2.35 (on arm64). This jump is problematic to several users who have internal requirements of using specific base images (e.g. RHE8).
- Some of the GHA changes that are making this more complicated: Node 16 actions will automatically be …

fix(core): build native libs against glibc 2.24

---

packages/core-bridge/src/runtime.rs
packages/test/src/test-prometheus.ts

Client metrics were being emitted without the prefix
Bug
1. Closes https://github.com/temporalio/sdk-typescript/issues/1440

Fix clients being created without prefixed metric meter

---

packages/client/src/workflow-client.ts
packages/test/src/test-integration-update.ts

Fixes #1372
- Repeatedly send `UpdateWorkflowExecution` until update is >= Accepted or >= requested stage; thereafter send `PollWorkflowExecutionUpdate` if necessary.
- Prevent SDK returning handle to update before it has reached Accepted state.
- Don't swallow gRPC timeout errors from server.

Evolve update long-poll implementation

---

packages/client/src/errors.ts
packages/client/src/workflow-client.ts
packages/test/src/test-integration-update.ts

Introduced a new exception `WorkflowUpdateRPCTimeoutOrCancelledError` that unifies grpc exceptions `DEADLINE_EXCEEDED` and `CANCELLED` during an update call for starting or polling for a result. 
1. Closes 
#1422 
Integration tests

feat(workflow): Unify GRPC::CANCELED and DEADLINE_EXCEEDED in an SDK Timeout exception for Update

---

packages/test/src/test-integration-update.ts
packages/workflow/src/interfaces.ts
packages/workflow/src/internals.ts
packages/workflow/src/update-scope.ts
packages/workflow/src/worker-interface.ts
packages/workflow/src/workflow.ts

A method `currentUpdateInfo()` has been added to workflow to obtain the name and id of a currently executing update handler from within. The solution uses AsyncLocalStorage to propagate  this information across asynchronous invocations. Calling `currentUpdateInfo()` within a workflow, but outside the async scope of an update handler invocation, returns `undefined`.
Facilitate deduplication of updates, particularly across CAN boundaries.
1. Closes 
#1317

feat(workflow): Expose updateId to update handlers

---

.github/workflows/ci.yml
packages/client/src/index.ts
packages/client/src/workflow-client.ts
packages/client/src/workflow-update-stage.ts
packages/test/src/test-integration-update-interceptors.ts
packages/test/src/test-integration-update.ts
packages/test/src/test-interface-type-safety.ts
packages/workflow/src/workflow.ts

Closes #1403
Make `startUpdate` require
```typescript
waitForStage: WorkflowUpdateStage.ACCEPTED
```
We decided to require this to make it explicit that the call -- despite being named `startXXX` -- blocks until a worker is available and accepts/rejects the update.

startUpdate require wait stage

---

.github/workflows/ci.yml
packages/client/src/workflow-client.ts
packages/test/src/helpers-integration.ts
packages/test/src/test-worker-lifecycle.ts
packages/test/src/test-worker-tuner.ts

- Remove CI's pinning on CLI 0.12.0.
- This was causing multiple CI flakes due to bugs that had already been fixed in server.
- Capture Dev Server logs.
- Hopefully, this may help understand some other flakes in the future.
- In SDK's internal tests, if using the `TEST_LOG_LEVEL` env variable, we now also set Core's logging to that same level.
- A few other very minor refactors and improvements here and there.
- In one of the Worker Tuner tests, disable the workflow cache, as the Resource Based Tuner seems not to prioritize allocation of permits to at least one non-sticky poller, which was causing flakes.

fix: Fix flakes in Worker Tuner and Workflow Update tests

---

packages/core-bridge/src/runtime.rs
packages/test/src/test-prometheus.ts

- Client metrics were being emitted without the prefix
- This is a backport of #1441 to 1.10.x.

Fix clients being created without prefixed metric meter (backport from #1441)

---

packages/client/src/connection.ts
packages/client/src/schedule-types.ts
packages/core-bridge/ts/index.ts
packages/testing/src/index.ts

- Update schedule catchup window default value in documentation enhancement — Fix #1471.
- Client Connection now accept responses up to 128MB — Fix #1470.
- Give more details about ephemeral server binaries caching and future stability of ephemeral server options. — Fix #1464.

docs: Clarify some drawbacks of ephemeral servers, and other minor fixes

---

.github/workflows/stress.yml

- Enabled file-based persistence on dev server for stress tests. This should hopefully resolve the consistent failure of nightly stress tests we have been observing since the workflow was modified to use CLI rather a Docker-based server (#1479)
- Also, persist server-side logs to a job artifact in case of failure to facilitate diagnosing eventual issues.

fix(ci): Enable file-based persistence on dev server for stress tests

---

packages/test/src/helpers-integration.ts

The webpack bundler INFO-level logging obscures test output and isn't needed:
```
2024-08-02T18:02:09.564Z [INFO] asset workflow-bundle-cf9fb26ab6b116d88d4e.js 2.67 MiB [emitted] [immutable] (name: main)
runtime modules 221 bytes 1 module
modules by path ../ 916 KiB 88 modules
modules by path ./lib/ 38.3 KiB
modules by path ./lib/*.js 35.8 KiB
./lib/test-integration-workflows-with-recorded-logs.js 17.9 KiB [built] [code generated]
./lib/helpers-integration.js 5.34 KiB [built] [code generated]
./lib/helpers.js 12.5 KiB [built] [code generated]
./lib/test-integration-workflows-with-recorded-logs-autogenerated-entrypoint.cjs 622 bytes [built] [code generated]
./lib/activities/interceptors.js 1.9 KiB [built] [code generated]
modules by path @temporalio/ 60 bytes
@temporalio/client (ignored) …
```

Silence webpack < WARN during integration tests

---

packages/common/src/failure.ts
packages/common/src/interfaces.ts
packages/test/src/helpers-integration.ts
packages/test/src/helpers.ts
packages/test/src/test-integration-workflows-with-recorded-logs.ts
packages/workflow/src/interfaces.ts
packages/workflow/src/internals.ts
packages/workflow/src/worker-interface.ts
packages/workflow/src/workflow.ts

Fixes #1434 and #1435.
- new workflow API to wait for all signal and update handlers to be finished:
`await workflow.condition(() => workflow.allHandlersFinished())`
- By default, warn when workflow exits with unfinished handlers, but not when a handler finishes due to workflow cancellation or workflow failure.
- Warnings controlled by `HandlerUnfinishedPolicy`

Warn on unfinished handlers and provide `workflow.allHandlersFinished()` API

---

.github/workflows/stress.yml

- Changed GHA runner for stress tests from `buildjet-4vcpu-ubuntu-2204` to `buildjet-8vcpu-ubuntu-2204`
- That test job has been failing recently with timeouts, and we suspect this might be due to runner's performance issues. If this is indeed the case, we will reevaluate at a later point.

chore: bump GHA runner for stress tests

---

.github/workflows/ci.yml
.github/workflows/stress.yml
package-lock.json
package.json
packages/docs/package.json

- Don't use `lerna` to run the `maybe-install-deps-and-build-docs` task as `packages/docs` is no longer considered a workspace package.
- There was apparently a LF character at the end of the `IS_MAIN_OR_RELEASE` env variable, preventing the `env.IS_MAIN_OR_RELEASE == 'true'` condition to evaluates to true, which in turn prevented deployment of docs to vercel.

fix(doc): Docs were no longer being built and deployed in CI

---

packages/client/src/index.ts

- `WorkflowExecutionAlreadyStartedError` was previously in `@temporalio/client`, but got recently moved to `@temporalio/common`. Add a reexport to avoid build issues.

fix(client): Reexport WorkflowExecutionAlreadyStartedError from `@temporalio/client`

---

.github/workflows/stress.yml

- Disable file-based persistence on dev server for stress tests, which we previously enabled in #1480. Though desirable in some aspects, enabling file-based persistence resulted in reducing tests performance, causing recurring timeout errors during nightly stress tests, as well as flakes during regular PR/main branch commit stress tests.
- For now, we can hopefully resolve the original issue by scaling up the GHA runners (which we already did in #1492). As a more stable solution, we can investigate at transitioning to Temporal Cloud.

fix(ci): Revert enabling file-based persistence on dev server for stress tests

---

CONTRIBUTING.md
packages/common/src/converter/payload-converter.ts
packages/common/src/internal-non-workflow/codec-helpers.ts
packages/core-bridge/Cargo.lock
packages/test/src/test-sinks.ts
packages/test/src/test-workflows.ts
packages/worker/src/worker.ts
packages/worker/src/workflow-codec-runner.ts
packages/worker/src/workflow/vm-shared.ts
packages/workflow/src/interfaces.ts
packages/workflow/src/internals.ts
packages/workflow/src/worker-interface.ts

- Update Core to a8150d5c.
- Updated Workflow Activation handling to expect `InitializeWorkflow` jobs, instead of `StartWorkflow` (fix #1511).
- Delay payload conversion of workflow's memo/SA/lastfailure/etc until we're inside the sandbox, as there's no guarantee that converted payloads are safe to transfer through the V8 message port to the worker thread.

chore: Update Core to a8150d5c (+job ordering update)

---

package-lock.json
packages/nyc-test-coverage/package.json

- Upgrade vulnerable dependency `webpack` in root package. It was missed in the previous batch upgrade due to some version pinning.

chore: Upgrade vulnerable dep (webpack) in root package (#1518)

---

packages/activity/src/index.ts

Using this as an opportunity to confirm my understanding is correct w.r.t `scheduledTimestampMs`.

Document timestamps in activity Info

---

packages/client/src/schedule-client.ts
packages/test/src/test-schedules.ts

Added the support for query for listing schedules and added test coverage on the changes.
1. Closes  [issue](https://github.com/temporalio/sdk-typescript/issues/1457)
Added a test to the above changes as discussed with @antlai-temporal .
Created four schedules with two schedules having a search attribute key and two of them not having search attribute keys and then listing with the key ensuring I got back two of them.
549 tests passed
2 tests skipped
9 tests todo

feat(Schedule): support query for listing schedules

---

packages/test/src/test-integration-workflows.ts

- Add integration tests for `workflowInfo().lastfailure`

test(workflow): Add integration tests for workflowInfo().lastfailure

---

.github/workflows/ci.yml
package-lock.json
package.json
packages/client/src/base-client.ts
packages/client/src/connection.ts
packages/client/src/types.ts
packages/cloud/README.md
packages/cloud/package.json
packages/cloud/src/cloud-operations-client.ts
packages/cloud/src/index.ts
packages/cloud/src/pkg.ts
packages/cloud/src/types.ts
packages/cloud/tsconfig.json
packages/common/src/internal-non-workflow/parse-host-uri.ts
packages/common/src/internal-non-workflow/tls-config.ts
packages/proto/scripts/compile-proto.js
packages/test/package.json
packages/test/src/test-client-cloud-operations.ts
packages/test/src/test-client-connection.ts
packages/test/src/test-parse-uri.ts
packages/test/tsconfig.json
packages/worker/src/connection-options.ts
tsconfig.prune.json

- Add experimental support for the Cloud Operations API. Resolves #1416.
- Introduced a new NPM package: `@temporalio/cloud`
- Introduced a new "high level Client" class, `CloudOperationsClient`. That needs to be distinct from the `Client` class, as Cloud Operations API goes through a different endpoint and requires different metadata.
- For now, the client provides no "high level" API. Users may use the low level, raw gRPC interface. They are responsible for providing the "temporal-cloud-api-version" metadata when doing so.
- Example usage:
```
const apiVersion = 2024-05-13-00;
// Note that this `connection` can't be shared with a `Client` object, they are distinct things
const connection = await CloudOperationsConnection.connect({
address: 'saas-api.tmprl.cloud:443',
apiKey,
tls: true, …
```

feat(client): Add experimental support for Cloud Operations API

---

packages/client/src/base-client.ts
packages/client/src/connection.ts
packages/client/src/errors.ts
packages/client/src/types.ts
packages/cloud/src/cloud-operations-client.ts
packages/test/src/test-client-connection.ts

- Added utility functions `isGrpcDeadlineError` and `isGrpcCancelledError` .
- Setting a deadline on gRPC calls (including all "high level" client calls made using our WorkflowClient) is a best practice, as not doing so may possibly result in waiting forever for a response that will never come. Yet, doing so implies that the user will need to check thrown errors, which turns this into a non-trivial exercise.
See for example the following snippet provided by a user. Note that they needed to add an explicit dependency on `@grpc/grpc-js` only for this purpose, as they need access to the `status` enum.
```
import { status as grpcStatus } from "@grpc/grpc-js";
import { isGrpcServiceError, ServiceError, WorkflowClient } from "@temporalio/client";
async function …
```

feat(client): Add utility functions isGrpcDeadlineError and isGrpcCancelledError

---

packages/core-bridge/Cargo.lock
packages/core-bridge/Cargo.toml
packages/core-bridge/src/conversions.rs
packages/core-bridge/src/conversions/slot_supplier_bridge.rs
packages/core-bridge/src/helpers.rs
packages/core-bridge/src/runtime.rs
packages/core-bridge/src/worker.rs
packages/core-bridge/ts/index.ts
packages/core-bridge/ts/worker-tuner.ts
packages/test/src/test-worker-tuner.ts
packages/worker/src/index.ts
packages/worker/src/worker-options.ts
packages/worker/src/worker-tuner.ts

Add user-implementable slot suppliers
Parity. Cool feature.
1. Closes 
Added tests
Yes, will be updating docs pages after all Core langs are done

User-implementable SlotSupplier

---

packages/client/src/client.ts
packages/client/src/schedule-client.ts
packages/client/src/schedule-helpers.ts
packages/client/src/schedule-types.ts
packages/client/src/task-queue-client.ts
packages/client/src/types.ts
packages/client/src/workflow-client.ts
packages/client/src/workflow-update-stage.ts
packages/common/src/activity-options.ts
packages/common/src/converter/failure-converter.ts
packages/common/src/failure.ts
packages/common/src/interfaces.ts
packages/common/src/internal-workflow/enums-helpers.ts
packages/common/src/internal-workflow/index.ts
packages/common/src/type-helpers.ts
packages/common/src/workflow-options.ts
packages/test/src/integration-tests-old.ts
packages/test/src/test-enums-helpers.ts
packages/test/src/test-integration-workflows.ts
packages/test/src/test-workflows.ts
packages/test/src/workflows/activity-failures.ts
packages/test/src/workflows/child-workflow-start-fail.ts
packages/test/src/workflows/testenv-test-workflows.ts
packages/workflow/src/interfaces.ts
packages/workflow/src/internals.ts
packages/workflow/src/workflow.ts

- This PR normalizes conventions around user facing `enums` in the TS SDK.
- More specifically, it features the following conventions:
- No more redundant prefixes on enum values.
For example:
```diff
await startChild(sleep, {
-   parentClosePolicy: ParentClosePolicy.PARENT_CLOSE_POLICY_ABANDON,
+   parentClosePolicy: ParentClosePolicy.ABANDON,
});
```
- No more 'UNSPECIFIED' values in user facing enums; TypeScript's `undefined` already means that.
- "Enum values" are now of type string, and the "enum" themselves are now implemented using `const` objects, with a string union type defined from all values of the const object. That makes it possible for users to simply pass the string representation of an enum value, without having to import and refer to the enum definition object. That's …

Normalize construction of user facing enums

---

packages/worker/src/worker.ts

- In case where an Activity Task would fail before the activity function was actually called, e.g. because there's no activity function registered for the activity name or because of a Payload Codec/Converter error, then the activity-specific RxJS Observer would never get closed, resulting in a memory leak.
- Also, added `numInFlightNonLocalActivities` and `numInFlightLocalActivities` in `WorkerStatus` (closes #1359).
- Tested locally with a custom load testing environment specifically meant to trigger the original memory leak.

fix(worker): Fix memory leak on non-existant activity

---

packages/test/src/activities/index.ts
packages/test/src/test-worker-activities.ts
packages/worker/src/activity.ts

- The activity cancellation's abort signal now has a `CancellationFailure` object as its `reason` property. This is useful when checking the `reason` as well as being what's thrown when `throwIfAborted()` is called (currently it's a `DOMException` as per [the default behavior](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/reason)).
- Unit test was added.
- Useful to know the Temporal reason (e.g. "TIMED_OUT").
- Easier to identify the abort as coming from Temporal.
- Same behavior whether you call `throwIfAborted()` or `await cancelled`.

fix(worker): abort reason should be CancellationFailure

---

.github/workflows/ci.yml
packages/core-bridge/ts/index.ts
packages/interceptors-opentelemetry/src/worker/index.ts
packages/interceptors-opentelemetry/src/workflow/index.ts
packages/test/src/test-otel.ts

- Add OpenTelemetry's Trace and Span IDs on log entries emitted using the Workflow and Activity context loggers, if appropriate. This allows log correlation on OpenTelemetry aggregators that supports that feature. Resolves #1425.
- Fix some misbehaving OTel-related tests.
- Add some clarifications regarding Runtime's OpenTelemetry metrics exporter configuration.

feat: Add OTel correlation metadata on emitted logs from Workflow and Activity context loggers

---

packages/client/src/helpers.ts
packages/client/src/types.ts
packages/client/src/workflow-client.ts
packages/test/src/test-integration-workflows.ts

Added a `count` method to the workflow client, a higher-level, user-friendlier option to using the corresponding GRPC method directly.
1. Closes #1069
Added an integration test.
Not sure

feat(client): add `client.workflow.count` high level API

---

packages/client/src/base-client.ts
packages/cloud/src/cloud-operations-client.ts

small typo fixes that I saw while onboarding and reading docs

small typo fixes while onboarding

---

packages/test/src/helpers-integration-multi-codec.ts
packages/test/src/helpers-integration.ts

Refactored existing integration testing helpers to allow for more flexibility, for example, to configure test setups with multiple test environments (as in `helpers-integration-multi-codec`).
This PR is part of splitting the large diff in #1583

Refactored existing integration testing helpers

---

packages/core-bridge/Cargo.lock
packages/test/src/test-integration-workflows-with-recorded-logs.ts

- Updated Rust dependencies
- Modified some Update integration tests to match the new error reported by Server 1.26.0 when Workflow completes after an update has been accepted, but before the update has been completed.
This PR targets the main branch.

chore: Upgrade Rust dependencies (main)

---

packages/core-bridge/Cargo.lock
packages/test/src/test-integration-workflows-with-recorded-logs.ts

- Updated Rust deps
- Modified some Update integration tests to match the new error reported by Server 1.26.0 when Workflow completes after an update has been accepted, but before the update has been completed.
This PR targets the 1.11.x branch.

chore: Update Rust deps (1.11.x branch) 

---

CONTRIBUTING.md

* Updated the environment setup portion of the contribution guide to use a numbered list instead of bullets.
When following this guide to setup my environment, I found myself skimming over the bulleted list instead of treating it as a set of tasks to complete. Using a numbered list for this section helps readability.

docs: Use numbered list for env setup in Contribution Guide

---

packages/interceptors-opentelemetry/README.md

On the OpenTelemetry interceptor README, I replaced a link to an anchor that no longer exists on the Temporal TypeScript SDK documentation page with a new link to an implementation sample of the OpenTelemetry interceptor in the samples-typescript repository.
To help people like myself looking for how to implement the interceptor.

docs: Replace broken otel doc link with sample link

---

.github/workflows/release.yml

- One of our CI test script was incorrectly pointing to the "next" branch of the sample-typescript repo, which is, ironically, very old and still depends on TS 4.x. This was causing build errors when running the SDK's sample tests.

fix(ci): do not use next branch for samples-typescript tests

---

packages/client/src/build-id-types.ts
packages/client/src/client.ts
packages/client/src/grpc-retry.ts
packages/client/src/task-queue-client.ts
packages/cloud/src/cloud-operations-client.ts
packages/cloud/src/index.ts
packages/common/src/activity-options.ts
packages/common/src/versioning-intent-enum.ts
packages/common/src/versioning-intent.ts
packages/core-bridge/ts/index.ts
packages/core-bridge/ts/worker-tuner.ts
packages/worker/src/connection-options.ts
packages/worker/src/worker-options.ts
packages/worker/src/worker-tuner.ts
packages/workflow/src/interfaces.ts

Reviewed and updated all `@experimental` annotations.
The following APIs are no longer tagged as experimental:
- Client gRPC Retry interceptor
- HTTP Proxy support
- Forwarding and filtering of Core's logs
- Configuration of Core's metrics
- `WorkerOptions.nonStickyToStickyPollRatio`
Text on remaining `@experimental` annotations have been updated to clearly and correctly reflect the expected future of each feature.

chore: Review all @experimental annotations

---

packages/core-bridge/ts/index.ts
packages/test/src/helpers-integration-multi-codec.ts
packages/test/src/helpers-integration.ts
packages/test/src/helpers.ts
packages/test/src/test-integration-workflows.ts
packages/test/src/test-schedules.ts
packages/test/src/test-typed-search-attributes.ts
packages/testing/src/index.ts

Can pass `searchAttributes` as a workflow options when creating test dev server (with or without time-skipping)
1. Closes #1447
Added integration test
No

Add search attributes to dev server

---

packages/client/src/schedule-client.ts
packages/client/src/schedule-types.ts
packages/test/src/test-schedules.ts

Allow schedules to update their search attributes.
1. Closes #1475 
Added integration test.
Unsure

Schedule update search attributes

---

.github/workflows/ci.yml
packages/client/src/errors.ts
packages/common/src/converter/failure-converter.ts
packages/common/src/internal-non-workflow/codec-helpers.ts
packages/test/src/test-failure-converter.ts
packages/workflow/src/interfaces.ts

💥 BREAKING CHANGE 💥 
Instead of expecting that the FailureConverter will always return a TemporalFailure.
This change is required for the FailureConverter to support Nexus HandlerError.
NOTE: a similar breaking change has been made in the Java SDK a little while ago: https://github.com/temporalio/sdk-java/pull/2365

fix!: Use plain Error in FailureConverter, WorkflowFailedError, and WorkflowUpdateFailedError

---

package-lock.json
packages/core-bridge/Cargo.lock
packages/core-bridge/Cargo.toml
packages/core-bridge/src/client.rs
packages/core-bridge/src/conversions.rs
packages/core-bridge/src/lib.rs
packages/core-bridge/src/runtime.rs
packages/core-bridge/src/worker.rs
packages/core-bridge/ts/errors.ts
packages/core-bridge/ts/index.ts
packages/test/src/run-a-workflow.ts
packages/test/src/test-native-connection.ts
packages/worker/package.json
packages/worker/src/connection.ts

This work enables both Nexus handlers and activities to get a `Client` powered by the `NativeConnection` of the `Worker` they are run in.
I left a TODO to support request cancelation via `withAbortSignal`, I may wait for @mjameswh's refactor before adding that.

NativeConnection powered Client

---

.github/workflows/ci.yml
.github/workflows/docs.yml
packages/client/src/helpers.ts
packages/client/src/types.ts
packages/test/src/test-integration-workflows.ts
packages/test/src/test-schedules.ts
packages/test/src/test-sinks.ts
packages/test/src/test-typed-search-attributes.ts
packages/worker/src/utils.ts
packages/worker/src/worker.ts
packages/workflow/src/index.ts
packages/workflow/src/interfaces.ts

Updated core
Expose root execution information from workflow description/execution info, and workflow info
1. Closes #1633 
Added test
Probably

Expose root execution info

---

packages/core-bridge/src/worker.rs
packages/core-bridge/ts/native.ts
packages/test/src/test-bridge.ts
packages/test/src/test-worker-poller-autoscale.ts
packages/test/src/workflows/index.ts
packages/test/src/workflows/wait-on-signal-then-activity.ts
packages/worker/src/worker-options.ts

*This is a cherry-pick of #1691, to get rid of dependency on #1679 and rebase over #1698.*
Expose options to opt-in to new poller autoscaling behavior
Poller autoscaling is cool!
1. Closes 
Added simple test. More meaningful tests are in Core, we just need to make sure option is passed properly here.

feat(worker): Expose Poller Automation

---

.github/workflows/ci.yml
.github/workflows/docs.yml
packages/common/src/internal-non-workflow/codec-types.ts
packages/core-bridge/Cargo.lock
packages/core-bridge/src/conversions.rs
packages/core-bridge/src/conversions/slot_supplier_bridge.rs
packages/core-bridge/src/worker.rs
packages/worker/src/workflow-codec-runner.ts
packages/workflow/src/internals.ts

chore: Update Core SDK in preparation for 1.11.8

---

packages/common/src/converter/failure-converter.ts
packages/common/src/failure.ts
packages/core-bridge/src/worker.rs
packages/test/src/test-integration-workflows-with-recorded-logs.ts
packages/worker/src/activity.ts

Added category to `ApplicationFailure`, users can now specify a category to signify the severity of their application failure. Application failure categories also map to different observability behaviours, namely, a BENIGN application failure downgrades log emissions to `DEBUG` for activity failures.
1. Closes #1672
small integration test

Add application failure category

---

.github/workflows/ci.yml
packages/common/src/activity-options.ts
packages/common/src/versioning-intent-enum.ts
packages/common/src/versioning-intent.ts
packages/core-bridge/src/metrics.rs
packages/workflow/src/interfaces.ts
packages/workflow/src/workflow.ts

VersioningIntent should've been deprecated along with the rest of the old versioning APIs when deployment based versioning was introduced
1. Closes 

Deprecate versioning intent

---

packages/core-bridge/index.js

- Bridge's error conversion logic now uses the `isPromise` node's utility function instead of an `instanceof Promise` check.
The later is prone to [Jest's globals differ from Node globals](https://github.com/jestjs/jest/issues/2549) bug (i.e. `somePromise instanceof Promise` may evaluate to `false` in some contexts), which would result in not converting errors thrown from the Rust side when Worker is run in Jest.
This has been causing Jest tests to fail with `ShutdownError: Worker has been shutdown` errors, using TS SDK 1.12.0.

fix(bridge): `instanceof Promise` was not giving correct results when run with Jest

---

packages/testing/src/mocking-activity-environment.ts

Set the default value of `MockActivityEnvironment`'s `workflowExecution.runId` to a UUID to better match the real implementation.
Makes the mock environment closer to the real environment.
1. Closes #1706
Made the change in my local environment and I was able to use `workflowExecution.runId` with UUID v5.
I don't think so

Set default `workflowExecution.runId` to a UUID in `MockActivityEnvironment`

---

package-lock.json
packages/common/package.json

Vercel introduced a breaking change to the `ms` package last night, causing a breaking change for the Typescript SDK due to us requiring `"ms": "^3.0.0-canary.1”`. Subsequently, users are getting bumped onto `ms@3.0.0-canary.202508252038` and encountering dependency issue `TypeError: (0 , ms_1.default) is not a function`.

fix: pin ms dependency to avoid breaking change

---

packages/client/src/async-completion-client.ts
packages/core-bridge/Cargo.lock
packages/core-bridge/src/worker.rs
packages/test/src/helpers-integration.ts
packages/test/src/test-integration-split-three.ts
packages/test/src/test-integration-workflows.ts
packages/worker/src/activity.ts
packages/worker/src/worker.ts

Added support to reset an activity. Cancellations due to reset are received through the heartbeat mechanism of the activity.
Part of activity operator work.
1. Closes #1693
Integration test
Likely

Activity reset

---

packages/client/src/interceptor-adapters.ts
packages/client/src/interceptors.ts
packages/client/src/types.ts
packages/client/src/workflow-client.ts
packages/client/src/workflow-options.ts
packages/core-bridge/src/worker.rs
packages/test/src/test-integration-workflows.ts
packages/worker/src/connection.ts

The main change to accommodate eager workflow start was adding `startWithDetails` to `WorkflowClientInterceptor` to support a (new) return type of `WorkflowStartOutput`. This allows us to return an object, giving us the ability to add new fields without issue - we add `eagerlyStarted` in this PR. This new interceptor method is injected if not defined at the internal `_start` call, and adapts the existing `start` interceptor method to use `startWithDetails`. We also define a new handle called `WorkflowHandleWithStartDetails` which extends the existing `WorkflowHandleWithFirstExecutionRunId`, which now includes whether the workflow was started eagerly or not. Adding fields to the handle is an adopted pattern in the TS SDK.
Support eager workflow start.
1. Closes #1348
2. How was this …

Eager Workflow Start
