temporalio/sdk-typescript

- packages/client/src/index.ts
- packages/test/src/test-integration.ts
- packages/worker/src/worker.ts
> Support failure in workflow activation

- packages/client/src/index.ts
- packages/test-interfaces/src/index.ts
- packages/test-workflows/src/cancel-timer-immediately.ts
- packages/test-workflows/src/cancel-timer-with-delay.ts
- packages/test-workflows/src/set-timeout.ts
- packages/test-workflows/src/signals.ts
- packages/test-workflows/src/simple-query.ts
- packages/test/src/test-integration.ts
- packages/test/src/test-workflows.ts
- packages/worker/src/worker.ts
- packages/workflow/src/common.ts
- packages/workflow/src/errors.ts
- packages/workflow/src/internals.ts
- scripts/gen-docs.js
As part of the alpha release preparations, we need to improve the docs and test coverage.
Added some more tests, some of which have been skipped for features that are not yet fully implemented such as queries, signals and activities.
> Enhance workflow client API and docs

- docs/determinism.md
- packages/proto/scripts/compile-proto.js
- packages/test-workflows/src/random.ts
- packages/test/src/test-integration.ts
- packages/test/src/test-time.ts
- packages/test/src/test-workflows.ts
- packages/worker/src/worker.ts
- packages/worker/src/workflow.ts
- packages/workflow/src/alea.ts
- packages/workflow/src/index.ts
- packages/workflow/src/internals.ts
- packages/workflow/src/time.ts
- packages/workflow/src/workflow.ts
Use randomness seed provided in activations and add a `uuid4` function for workflows.
Added relevant workflow tests.
uuid4 was documented.
Added a doc about determinism in workflows.
> Use randomness seed provided in activations

- package-lock.json
- packages/client/package.json
- packages/client/src/index.ts
- packages/worker/package.json
Closes #59 
Tested using the e2e test suite.
> Replace grpc package with @grpc/grpc-js

- etc/verdaccio-config.yaml
Fixes build for the project
verdaccio released a new version which broke the build
> Update verdaccio config for v5

- CONTRIBUTING.md
- docs/sdk-structure.md
- packages/create-project/lib/index.js
- packages/create-project/src/index.ts
- packages/meta/README.md
- packages/proto/scripts/module-header.txt
- packages/test-workflows/src/global-overrides.ts
- packages/test/src/test-workflows.ts
- packages/workflow/src/errors.ts
- packages/workflow/src/index.ts
- packages/workflow/src/init.ts
- scripts/test-example.js
- Move SDK structure doc back into this repo
- Add `npm start` script in the package initializer
- Rename generated test.ts to schedule-workflow.ts
- Revise note about user feedback
- Mock instead of delete `Weak*` constructors
Address comments from docs review with @sw-yx 
1. How was this tested:
Added relevant test
2. Any docs updates needed?
This PR is mostly docs updates.
> Make changes from docs review

- packages/test-activities/src/index.ts
- packages/test-interfaces/src/index.ts
- packages/test-workflows/src/activity-failure.ts
- packages/test-workflows/src/cancel-http-request.ts
- packages/test/src/helpers.ts
- packages/test/src/mock-native-worker.ts
- packages/test/src/test-integration.ts
- packages/test/src/test-worker-activities.ts
- packages/test/src/test-worker-lifecycle.ts
- packages/test/src/zeroes-http-server.ts
- packages/worker/native/Cargo.lock
- packages/worker/native/Cargo.toml
- packages/worker/native/index.d.ts
- packages/worker/native/src/lib.rs
- packages/worker/src/activity.ts
- packages/worker/src/logger.ts
- packages/worker/src/worker.ts
- packages/workflow/src/internals.ts
- scripts/clean.js
- scripts/test-example.js
- Update core for heartbeat support
- Add activity cancellation test
- Fix shutdown issue
Get closer to the alpha release
1. Closes issue:
Closes #61 
Closes #47 
Added an extra test and shutdown success assertion.
Update the bridge docs
> Update core for heartbeat support, add activity cancellation test

- packages/test/src/test-worker-lifecycle.ts
- packages/worker/native/src/lib.rs
- packages/worker/src/worker.ts
- packages/workflow/src/errors.ts
> Implement workflow cache cleanup

- package-lock.json
- packages/activity/README.md
- packages/activity/package.json
- packages/client/README.md
- packages/client/package.json
- packages/create-project/README.md
- packages/meta/README.md
- packages/proto/README.md
- packages/proto/package.json
- packages/worker/README.md
- packages/worker/package.json
- packages/worker/src/worker.ts
- packages/workflow/README.md
- packages/workflow/package.json
- Update README
- Minor API reference changes
> Prepare for alpha release

- packages/activity/package.json
- packages/client/package.json
- packages/create-project/package.json
- packages/meta/package.json
- packages/proto/package.json
- packages/test-activities/package.json
- packages/test-workflows/package.json
- packages/test/package.json
- packages/worker/package.json
- packages/workflow/package.json
- @temporalio/activity@0.1.5
- @temporalio/client@0.1.5
- @temporalio/create@0.1.6
- temporalio@0.1.7
- @temporalio/proto@0.1.5
- @temporalio/test-activities@0.1.5
- @temporalio/test-workflows@0.1.5
- @temporalio/test@0.1.5
- @temporalio/worker@0.1.5
- @temporalio/workflow@0.1.5
> Publish the alpha release

- .github/workflows/ci.yml
- docs/building.md
- packages/create-project/samples/client-mtls-from-sample.ts
- packages/create-project/samples/worker-mtls-from-sample.ts
- packages/test/src/bench.ts
- packages/test/src/mock-native-worker.ts
- packages/worker/native/Cargo.lock
- packages/worker/native/index.d.ts
- packages/worker/native/src/lib.rs
- packages/worker/src/worker.ts
See commits
Basic feature for the SDK
Closes #87 
Standard test suite and manual run of `worker-mtls-from-sample.ts`.
(Currently fails to connect to the sample server with the error below)
```
[TransportError: transport error: error trying to connect: invalid URL, scheme is missing]
```
I'll update the documentation site after this is merged.
> Add Worker grpc TLS options

- packages/worker/src/isolate-builder.ts
A couple errors happen if you don't have an `src/activities` directory. First, you get `Error: ENOENT: no such file or directory, scandir '/app/src/activities'` because `readdir()` throws. Once that's fixed, you still get a `Error: ENOENT: no such file or directory, open '/src/main.js'` if you have an empty activities map because `registerActivities()` creates the directory recursively, but `genEntrypoint()` does not.
Both of these errors are a bit hard to grok, especially the `src/main.js` one. Either way, should be able to create a project with no activities.
> fix(worker): allow creating worker with zero activities

- packages/client/src/index.ts
Noticed a couple of minor typos while walking through the code
> docs(client): Fix a couple typos in comments

- packages/worker/src/worker.ts
Added a note to the error message about how to fix the error
I ran into this while trying to set up a project manually and needed to do some searching through the code to figure out how to fix it.
> fix(worker): Make isolate error message suggest a fix

- commitlint.config.js
- package-lock.json
- packages/test/src/interfaces/dependencies.ts
- packages/test/src/mock-native-worker.ts
- packages/test/src/test-dependencies.ts
- packages/test/src/test-workflows.ts
- packages/test/src/worker/external-logger-example.ts
- packages/test/src/workflows/dependencies.ts
- packages/test/src/workflows/ignored-dependencies.ts
- packages/test/src/workflows/log-before-timing-out.ts
- packages/test/src/workflows/log-sample.ts
- packages/test/src/workflows/top-level-dependencies.ts
- packages/worker/package.json
- packages/worker/src/dependencies.ts
- packages/worker/src/index.ts
- packages/worker/src/worker.ts
- packages/worker/src/workflow.ts
- packages/workflow/src/dependencies.ts
- packages/workflow/src/index.ts
- packages/workflow/src/init.ts
- packages/workflow/src/interfaces.ts
- packages/workflow/src/internals.ts
- packages/workflow/src/workflow.ts
Implements proposal: https://github.com/temporalio/proposals/blob/acbe448d9325bb3914c91e693019c66f21646d07/node/logging-and-metrics-for-user-code.md
1. Closes issues:
Closes #53
Closes #108
Added relevant tests
Will update the docs site once before this is released.
> feat: Support injecting external dependencies into the Workflow isolate

- .eslintrc
- package-lock.json
- package.json
- packages/client/src/index.ts
- packages/client/src/interceptors.ts
- packages/client/src/types.ts
- packages/client/src/workflow-options.ts
- packages/test/src/activities/index.ts
- packages/test/src/bench.ts
- packages/test/src/test-interceptors.ts
- packages/test/src/test-workflows.ts
- packages/test/src/workflows/cancel-activity-after-first-completion.ts
- packages/test/src/workflows/interceptor-example.ts
- packages/worker/package.json
- packages/worker/src/activity.ts
- packages/worker/src/index.ts
- packages/worker/src/interceptors.ts
- packages/worker/src/isolate-builder.ts
- packages/worker/src/tracing.ts
- packages/worker/src/worker.ts
- packages/worker/src/workflow.ts
- packages/workflow/src/index.ts
- packages/workflow/src/init.ts
- packages/workflow/src/interceptors.ts
- packages/workflow/src/interfaces.ts
- packages/workflow/src/internals.ts
- packages/workflow/src/type-helpers.ts
- packages/workflow/src/workflow.ts
Implements proposal [#25](https://github.com/temporalio/proposals/blob/79357b9268dccccf1f8031f36e1714d4f07c9875/node/interceptors.md)
I'll add a page in the documentation site.
In an upcoming PR I'll submit the opentelemetry interceptor package I'm working on.
> Interceptors

- packages/core-bridge/Cargo.lock
- packages/core-bridge/index.d.ts
- packages/core-bridge/src/lib.rs
- packages/create-project/samples/worker-mtls.ts
- packages/create-project/samples/worker.ts
- packages/test/src/bench.ts
- packages/test/src/mock-native-worker.ts
- packages/test/src/test-core.ts
- packages/test/src/test-server-options.ts
- packages/test/src/test-workflows.ts
- packages/worker/src/core.ts
- packages/worker/src/index.ts
- packages/worker/src/isolate-builder.ts
- packages/worker/src/pkg.ts
- packages/worker/src/server-options.ts
- packages/worker/src/tracing.ts
- packages/worker/src/worker.ts
Depends on https://github.com/temporalio/sdk-core/pull/132
> Sticky and multi worker

- packages/test/src/test-workflows.ts
- packages/worker/src/isolate-builder.ts
> fix: Explicitly set isolate devtool to cheap-source-map

- CONTRIBUTING.md
- LICENSE.md
- docs/building.md
- docs/sdk-structure.md
- packages/activity/README.md
- packages/client/README.md
- packages/core-bridge/README.md
- packages/create-project/README.md
- packages/docs/docs/index.md
- packages/docs/docusaurus.config.js
- packages/meta/README.md
- packages/proto/README.md
- packages/worker/README.md
- packages/worker/src/dependencies.ts
- packages/worker/src/workflow.ts
- packages/workflow/README.md
- packages/workflow/src/dependencies.ts
- packages/workflow/src/worker-interface.ts
@djmagee I'm assuming this is the sort of thing that makes you happy :)
> chore: Use correct Node.js trademark everywhere

- packages/client/src/workflow-client.ts
- packages/interceptors-opentelemetry/src/client/index.ts
- packages/interceptors-opentelemetry/src/worker/index.ts
- packages/interceptors-opentelemetry/src/workflow/index.ts
- packages/test/src/test-data-converter.ts
- packages/test/src/test-integration.ts
- packages/test/src/test-interceptors.ts
- packages/test/src/test-worker-activities.ts
- packages/test/src/test-workflows.ts
- packages/test/src/workflows/interceptor-example.ts
- packages/worker/src/activity.ts
- packages/worker/src/worker.ts
- packages/worker/src/workflow.ts
- packages/workflow/src/converter/data-converter.ts
- packages/workflow/src/converter/payload-converter.ts
- packages/workflow/src/internals.ts
- packages/workflow/src/worker-interface.ts
- packages/workflow/src/workflow.ts
Switched the data converter interface to be async to support non-blocking encryption and compression.
CC @rylandg @robholland
> feat!: Use async data converter interface

- package.json
Added `engines` to `package.json`, including required version of rustc. See [these docs](https://classic.yarnpkg.com/en/docs/package-json/#toc-system).
Had some trouble compiling today - ended up being I just needed to upgrade rustc. Would be good to know what version of rust is required, the only way I figured that out was checking the CI logs for what rust version the CI used.
1. Closes 
> chore: Add engines to package.json

- packages/test/src/bench.ts
Makes bench wait on temporal server by adding a retry loop for the namespace creation.
This is better than running a separate script because it makes bench more self contained.
> chore: Make bench wait for temporal during namespace creation

- packages/core-bridge/src/lib.rs
- packages/test/src/mock-native-worker.ts
- packages/test/src/perf/starter.ts
- packages/worker/src/activity.ts
- packages/worker/src/isolate-builder.ts
- packages/worker/src/worker.ts
Some leftovers from the perf work.
Using a pool of isolates seems to help performance and improves the worker slow down issue (#162).
> Moar perf stuff

- packages/test/src/activities/index.ts
- packages/test/src/interfaces/index.ts
- packages/test/src/test-integration.ts
- packages/test/src/workflows/cancel-fake-progress.ts
- packages/test/src/workflows/cancel-http-request.ts
- packages/workflow/src/index.ts
- packages/workflow/src/interfaces.ts
- packages/workflow/src/workflow.ts
> feat(workflow): Expose ActivityCancellationType

- commitlint.config.js
- packages/core-bridge/Cargo.lock
- packages/core-bridge/Cargo.toml
- packages/core-bridge/src/lib.rs
- packages/meta/README.md
- packages/test/src/activities/index.ts
- packages/test/src/perf/args.ts
- packages/test/src/perf/starter.ts
- packages/test/src/perf/worker.ts
- packages/worker/src/workflow.ts
> Fix slowdown

- packages/activity/src/index.ts
- packages/client/src/errors.ts
- packages/client/src/index.ts
- packages/client/src/workflow-client.ts
- packages/common/src/errors.ts
- packages/common/src/failure.ts
- packages/common/src/index.ts
- packages/common/src/interfaces.ts
- packages/common/src/time.ts
- packages/core-bridge/src/lib.rs
- packages/proto/lib/index.js
- packages/proto/scripts/compile-proto.js
- packages/test/src/activities/failure-tester.ts
- packages/test/src/helpers.ts
- packages/test/src/mock-native-worker.ts
- packages/test/src/test-integration.ts
- packages/test/src/test-interceptors.ts
- packages/test/src/test-worker-activities.ts
- packages/test/src/test-workflows.ts
- packages/test/src/workflows/activity-failure.ts
- packages/test/src/workflows/activity-failures.ts
- packages/worker/src/activity.ts
- packages/worker/src/isolate-context-provider.ts
- packages/worker/src/worker.ts
- packages/workflow/src/internals.ts
- packages/workflow/src/workflow.ts
Closes #146
We still need to figure out what to do for activity cancellation.
> Port failure classes from Java SDK

- packages/client/src/workflow-client.ts
- packages/client/src/workflow-options.ts
- packages/common/src/converter/data-converter.ts
- packages/common/src/converter/payload-converter.ts
- packages/common/src/failure.ts
- packages/common/src/index.ts
- packages/common/src/type-helpers.ts
- packages/common/src/workflow-options.ts
- packages/common/src/workflow-stub.ts
- packages/test/src/test-integration.ts
- packages/test/src/test-workflows.ts
- packages/test/src/workflows/child-workflow-cancel.ts
- packages/test/src/workflows/child-workflow-failure.ts
- packages/test/src/workflows/child-workflow-invoke.ts
- packages/test/src/workflows/child-workflow-start-fail.ts
- packages/test/src/workflows/child-workflow-termination.ts
- packages/test/src/workflows/child-workflow-timeout.ts
- packages/test/src/workflows/interceptor-example.ts
- packages/workflow/src/errors.ts
- packages/workflow/src/index.ts
- packages/workflow/src/interceptors.ts
- packages/workflow/src/interfaces.ts
- packages/workflow/src/internals.ts
- packages/workflow/src/worker-interface.ts
- packages/workflow/src/workflow.ts
This should not be merged until https://github.com/temporalio/sdk-core/pull/163 is merged.
We should bring back the incremented sequence for generating correlation IDs between lang and core.
That will be done in a later PR.
> Child Workflows

- CONTRIBUTING.md
> docs: Clarify environment setup

- .eslintrc
- packages/test/src/test-integration.ts
- packages/test/src/test-workflows.ts
- packages/test/src/workflows/deprecate-patch.ts
- packages/test/src/workflows/patched.ts
- packages/worker/src/workflow.ts
- packages/workflow/src/index.ts
- packages/workflow/src/internals.ts
- packages/workflow/src/workflow.ts
Added `patched` and `deprecatePatch` workflow APIs
Support changes to live workflows
1. Closes https://github.com/temporalio/sdk-node/issues/68
Added UTs and ITs
The nitty gritty logic is well tested in core
Definitely. We need to explain this one bigtime. Refer to https://github.com/temporalio/proposals/blob/master/core/versions_2.0.md
> New `patched` API formerly known as versioning

- packages/docs/sidebars.js
Closes #195
Closes #196 
CC @lorensr
> docs: Nest items in sidebar

- packages/test/src/test-worker-no-workflows.ts
- packages/test/src/workflows/run-activity-in-different-task-queue.ts
- packages/worker/src/worker.ts
> fix(worker): Allow creating a Worker with no workflows

- .buildkite/docker/docker-compose-telem.yaml
- .buildkite/docker/docker-compose.yaml
- etc/prometheus.yaml
- package-lock.json
- packages/core-bridge/Cargo.lock
- packages/core-bridge/Cargo.toml
- packages/core-bridge/index.d.ts
- packages/core-bridge/src/lib.rs
- packages/test/src/load/worker.ts
- packages/test/src/mock-native-worker.ts
- packages/test/src/test-dependencies.ts
- packages/test/src/test-integration.ts
- packages/test/src/test-interceptors.ts
- packages/worker/src/core.ts
- packages/worker/src/logger.ts
- packages/worker/src/worker.ts
Import exported logs from core. Depends on https://github.com/temporalio/sdk-core/pull/189
Easy-to-enable debuggability for users
1. Relates to https://github.com/temporalio/sdk-core/issues/85
Integ tests
Probably need to have a little section on various telemetry / logging options
> Ability to import logs from core

- packages/worker/src/core.ts
> Fix log gather error on shutdown

- packages/test/src/load/setup.ts
- packages/test/src/load/starter.ts
Started writing a review for #257 and it got too long so I made this PR instead.
@Sushisource
> test: Suggest changes to load test structure

- .buildkite/docker/docker-compose.yaml
- package-lock.json
- packages/activity/src/index.ts
- packages/core-bridge/index.d.ts
- packages/core-bridge/src/lib.rs
- packages/test/src/interfaces/index.ts
- packages/test/src/test-dependencies.ts
- packages/test/src/test-logger.ts
- packages/test/src/test-workflows.ts
- packages/worker/package.json
- packages/worker/src/core.ts
- packages/worker/src/logger.ts
- packages/worker/src/worker.ts
- packages/worker/workflow-isolate-extension.cc
- packages/workflow/src/cancellation-scope.ts
- packages/workflow/src/index.ts
- packages/workflow/src/workflow.ts
Closes #246 
Closes #271 
Closes #270
Closes #266
> Pre beta stabilization

- package-lock.json
- packages/core-bridge/Cargo.lock
- packages/core-bridge/Cargo.toml
- packages/core-bridge/index.d.ts
- packages/core-bridge/scripts/build.js
- packages/core-bridge/src/conversions.rs
- packages/core-bridge/src/lib.rs
- packages/test/src/mock-native-worker.ts
- packages/test/src/test-otel.ts
- packages/test/src/test-server-options.ts
- packages/worker/src/core.ts
- packages/worker/src/server-options.ts
- packages/worker/src/worker.ts
Sdk name/version info now passed through into core
Spans are now attached between node/core properly!
Server can change behavior based on client. Version tracking, etc.
Cool spans!
1. Closes https://github.com/temporalio/sdk-core/issues/85
Added a test which can be run by hand so the runner can inspect the spans in Jaeger or whatever. Verified spans are now connected.
> Pass client/version info to core & core update & set span contexts!

- packages/client/src/workflow-client.ts
- packages/client/src/workflow-options.ts
- packages/common/src/workflow-options.ts
- packages/test/src/load/starter.ts
- packages/test/src/test-integration.ts
- packages/test/src/test-logger.ts
- packages/test/src/test-workflows.ts
- packages/test/src/workflows/child-workflow-unregistered.ts
- packages/test/src/workflows/date.ts
- packages/test/src/workflows/index.ts
- packages/worker/src/logger.ts
- packages/worker/src/server-options.ts
- packages/worker/src/worker.ts
- packages/worker/src/workflow.ts
- packages/workflow/src/interfaces.ts
- packages/workflow/src/worker-interface.ts
- packages/workflow/src/workflow.ts
Closes #286 
Closes #287 
Closes #276
> Minor fixes

- packages/test/src/test-interceptors.ts
- packages/worker/src/worker.ts
- packages/workflow/src/internals.ts
> fix: Delay query processing until workflow has started

- packages/core-bridge/src/conversions.rs
> chore: Change client name string to `temporal-typescript`

- packages/worker/src/worker-options.ts
> feat(worker): Add SIGUSR2 to default list of shutdown signals

- packages/core-bridge/Cargo.lock
Update core
We could end up producing a fatal error if polling was failing for a long time. Avoids that.
1. Closes 
> fix: Update core to gain infinite poll retries

- CHANGELOG.md
> chore: Prepare CHANGELOG for 0.14.0 release

- package-lock.json
- packages/core-bridge/index.d.ts
- packages/core-bridge/package.json
- packages/worker/src/workflow/interface.ts
Fixes issues reported on slack: https://temporalio.slack.com/archives/C01DKSMU94L/p1636418244123100
> fix: Fix type imports

- packages/test/src/test-workflows.ts
- packages/test/src/workflows/index.ts
- packages/test/src/workflows/patched-top-level.ts
- packages/worker/src/worker.ts
- packages/worker/src/workflow/interface.ts
- packages/worker/src/workflow/isolated-vm.ts
- packages/workflow/src/worker-interface.ts
- packages/workflow/src/workflow.ts
> fix(workflow): Throw if patches are used at Workflow top level

- docs/building.md
- etc/mac-cargo-config.toml
- packages/core-bridge/scripts/build.js
> feat: Support complication on Mac for aarch64-unknown-linux-gnu

- packages/core-bridge/Cargo.lock
See https://github.com/temporalio/sdk-core/pull/225
Bugfix goodness
1. Closes 
> fix: Update core to receive bugfixes

- .github/workflows/ci.yml
- .prettierignore
- docs/building.md
- package-lock.json
- package.json
- packages/common/src/failure.ts
- packages/core-bridge/package.json
- packages/core-bridge/scripts/build.js
- packages/meta/README.md
- packages/test/src/test-resolve-node-modules.ts
- packages/worker/binding.gyp
- packages/worker/src/workflow/bundler.ts
- scripts/init-from-verdaccio.js
- scripts/publish-to-verdaccio.js
- scripts/registry.js
- scripts/utils.js
Closes #12 
Closes #379 
Tests npm init on Windows (#22)
Replaces #381 and adds tests.
Special thanks to @cons0l3 for the contribution, who will be added as co author.
> Support Windows build

- CHANGELOG.md
> chore: Prepare CHANGELOG for 0.16.3 release

- packages/worker/src/index.ts
> chore(docs): Expose worker.CoreOptions

- packages/common/src/workflow-options.ts
- packages/worker/src/index.ts
- packages/worker/src/logger.ts
- packages/worker/src/workflow/bundler.ts
- chore(docs): Prevent __namedParameters params from being generated
- chore(docs): Expose BundleOptions
Current docs:
Proposed:
> Expose BundleOptions and remove __namedParameters

- packages/test/src/test-workflows.ts
- packages/worker/src/interceptors.ts
- packages/worker/src/worker-options.ts
- packages/worker/src/worker.ts
- packages/worker/src/workflow/bundler.ts
- packages/worker/src/workflow/vm.ts
- packages/workflow/src/internals.ts
- packages/workflow/src/worker-interface.ts
> fix: Use bundled Workflow interceptors

- packages/activity/src/index.ts
- packages/client/src/async-completion-client.ts
- packages/client/src/index.ts
- packages/common/src/index.ts
- packages/common/src/utils.ts
- packages/test/src/activities/async-completer.ts
- packages/test/src/test-async-completion.ts
- packages/test/src/workflows/async-activity-completion-tester.ts
- packages/test/src/workflows/index.ts
- packages/worker/src/activity.ts
- packages/worker/src/core.ts
- packages/worker/src/utils.ts
- packages/workflow/src/workflow.ts
> feat: Implement async Activity completion

- packages/core-bridge/Cargo.lock
- packages/core-bridge/Cargo.toml
- packages/core-bridge/src/conversions.rs
- packages/core-bridge/src/lib.rs
- packages/test/src/test-interceptors.ts
- packages/test/src/test-worker-activities.ts
- packages/test/src/test-workflows.ts
- packages/worker/src/activity.ts
- packages/worker/src/worker.ts
Switch back to core master branch. Includes local activity work.
Prepare for local activity implementation
1. Closes 
All existing tests passing
> Update Core back to master

- .github/workflows/ci.yml
- package-lock.json
- package.json
- packages/core-bridge/Cargo.lock
- packages/core-bridge/Cargo.toml
- packages/core-bridge/package.json
- packages/core-bridge/scripts/build.js
* Use full LTO & no debug symbols for Rust release builds to decrease package size
* Build debug for local development, release for CI & cross-compile/packaging
* Don't lint on every platform
* Don't double-build rust in cross compile jobs
Next PR:
* Add integration with sdk-features repo
Faster CI, smaller packages, features coverage
1. Closes 
> Optimize rust building in CI

- packages/core-bridge/src/errors.rs
Currently if you import the `@temporalio/worker` module more than once, you run into a Rust panic because `native.registerErrors` is called once per import:
https://github.com/temporalio/sdk-typescript/blob/2232465a4f9b0cade28f0c21c2d7856053678728/packages/worker/src/worker.ts#L64
and the underlying Rust `register_errors` function can only be called once:
https://github.com/temporalio/sdk-typescript/blob/2232465a4f9b0cade28f0c21c2d7856053678728/packages/core-bridge/src/errors.rs#L67
This PR adds a check to see if `register_errors` has been called already, and makes the function do nothing if it has.
#469 
1. Closes #469 
I made the changes locally and then pointed my project at my version of the Temporal Typescript SDK. I then ran the same sequential integration …
> fix(worker): Don't register errors more than once allowing for multiple module imports w/o panic

- CHANGELOG.md
> docs: Add breaking change notice to CHANGELOG for v0.18.0

- packages/activity/src/index.ts
- packages/test/src/test-worker-activities.ts
- packages/test/src/test-worker-heartbeats.ts
- packages/worker/src/activity.ts
- packages/worker/src/rxutils.ts
- packages/worker/src/worker.ts
- Flush last heartbeat on Activity failure
- Ensure ordering of heartbeats when custom payload codec is used
- Discard heartbeats if activity sends them faster than payload codec
can process them
> fix(worker): Enhance and fix heartbeat behavior

- package-lock.json
- packages/worker/package-lock.json
- packages/worker/package.json
- packages/worker/src/workflow/bundler.ts
SWC is much faster and robust than TSC. It's written in Rust and can be used with webpack by using their swc-loader.
Replaced ts-loader by swc-loader.
1. Closes 
- We've been testing it in dev for a while by using "npm patch-package" and no errors so far.
> use swc-loader instead of ts-loader

- packages/client/src/workflow-client.ts
- packages/common/src/converter/data-converter.ts
- packages/common/src/converter/types.ts
- packages/internal-non-workflow-common/package.json
- packages/internal-non-workflow-common/src/codec-helpers.ts
- packages/internal-non-workflow-common/src/codec-types.ts
- packages/internal-non-workflow-common/src/index.ts
- packages/test/src/integration-tests.ts
- packages/worker/src/workflow-codec-runner.ts
- packages/workflow/src/workflow.ts
Anything else that the default data converter should be used on?
> fix: Use default data converter for search attributes

- CHANGELOG.md
- packages/common/src/failure.ts
A couple more things to add once they're merged
> docs: Add 0.19.0 to CHANGELOG

- .gitignore
- package-lock.json
- package.json
- packages/activity/src/index.ts
- packages/test/package.json
- packages/test/src/load/all-in-one.ts
- packages/test/src/load/setup.ts
- packages/test/src/test-mockactivityenv.ts
- packages/test/src/test-testenvironment.ts
- packages/test/tsconfig.json
- packages/testing/package.json
- packages/testing/scripts/download-test-server.mjs
- packages/testing/src/child-process.ts
- packages/testing/src/index.ts
- packages/testing/src/utils.ts
- packages/testing/tsconfig.json
Initial work, missing features:
- No ability to fast forward time outside of a workflow
- No ability to toggle normal / time skipped mode
> feat: Add testing framework

- packages/test/src/mocks/workflows-with-node-dependencies/example/client.ts
- packages/test/src/mocks/workflows-with-node-dependencies/example/index.ts
- packages/test/src/mocks/workflows-with-node-dependencies/example/models.ts
- packages/test/src/mocks/workflows-with-node-dependencies/issue-516.ts
- packages/test/src/test-worker-from-bundle.ts
- packages/test/src/test-workflows.ts
- packages/worker/src/worker-options.ts
- packages/worker/src/worker.ts
- packages/worker/src/workflow/bundler.ts
Picks up work started by @mjameswh in #519
> feat(workflow-bundler): Allow ignoring modules for Webpack build

- packages/client/src/workflow-client.ts
- packages/workflow/src/cancellation-scope.ts
Related user question: https://temporalio.slack.com/archives/C01DKSMU94L/p1647843821683779?thread_ts=1647841169.444809&cid=C01DKSMU94L
> docs(client): Add to getHandle documentation

- packages/core-bridge/Cargo.lock
Update sdk-core submodule and cargo deps
> fix(core): Fix worker responding with empty commands during query of uncached workflow

- .github/workflows/ci.yml
- packages/client/src/interceptors.ts
- packages/client/src/workflow-client.ts
- packages/test/src/test-interceptors.ts
- packages/test/src/workflows/index.ts
- packages/test/src/workflows/interceptor-example.ts
- packages/workflow/src/interceptors.ts
- packages/workflow/src/internals.ts
- packages/workflow/src/workflow.ts
> feat: Support headers to signals and queries with interceptors

- .github/workflows/nightly.yml
Need to merge this to main before it can be tested. Thanks GHA.
> Add GHA workflow

- packages/test/src/test-payload-converter.ts
- packages/workflow/src/workflow-handle.ts
To answer this question: https://temporalio.slack.com/archives/C01DKSMU94L/p1651439285108119
> Add method note to ExternalWorkflowHandle

- packages/test/src/query-perf.ts
- packages/test/src/workflows/long-history-generator.ts
Useful for measuring query performance in different scenarios.
Does not run automatically.
> test: Add query-perf script

- packages/test/src/load/all-in-one.ts
- packages/test/src/load/args.ts
- packages/test/src/test-worker-heartbeats.ts
- packages/worker/src/worker.ts
Closes #649
2 leaks were discovered and fixed from "recent" Activity refactoring.
I'll set up alerts for our nightly tests to make sure this never happens again.
> fix(worker): Fix memory leaks

- CHANGELOG.md
Want to release this and add a sample showing how to use the test framework
> Prepare CHANGELOG for 0.23.2 release

- scripts/wait-on-temporal.mjs
Makes it a little shorter/simpler
> ci: Use top-level await in wait-on-temporal.mjs

- packages/meta/README.md
Part of this [migration](https://github.com/temporalio/documentation/pull/1136) there is a new URL.
1. Closes 
> Updating Doc URLs

- packages/client/src/connection.ts
- packages/client/src/workflow-client.ts
- packages/workflow/src/cancellation-scope.ts
Mostly feedback raised by @lorensr in #682
> chore: Address feedback from connection refactor PR

- packages/worker/src/worker-options.ts
> fix(docs): Remove maxIsolateMemoryMB

- packages/client/src/connection.ts
- packages/client/src/types.ts
- packages/common/src/converter/types.ts
- packages/core-bridge/Cargo.lock
- packages/core-bridge/Cargo.toml
- packages/core-bridge/index.d.ts
- packages/core-bridge/src/conversions.rs
- packages/core-bridge/src/lib.rs
- packages/internal-workflow-common/src/interceptors.ts
- packages/internal-workflow-common/src/interfaces.ts
- packages/internal-workflow-common/src/workflow-options.ts
- packages/proto/scripts/compile-proto.js
- packages/test/src/integration-tests.ts
- packages/test/src/test-workflows.ts
- packages/worker/src/connection-options.ts
- packages/worker/src/runtime.ts
- packages/worker/src/worker-options.ts
- packages/worker/src/worker.ts
- packages/worker/src/workflow-codec-runner.ts
- packages/workflow/src/internals.ts
- packages/workflow/src/workflow.ts
- Closes #697 
- Exposes `operatorService` on client `Connection`.
> chore: Upgrade to latest Core

- .github/workflows/ci.yml
- etc/aarch64-linux-cargo-config.toml
- etc/mac-cargo-config.toml
Trying this out to see if it'll work
> chore: Build bridge for arm linux

- packages/workflow/src/workflow.ts
> fix(workflow): executeChild returns Promise<WorfkflowResultType<T>>

- packages/internal-workflow-common/src/workflow-options.ts
- packages/workflow/src/interfaces.ts
Spencer checked `ChildWorkflowCancellationType`
> docs: Document ParentClosePolicy and ChildWorkflowCancellationType

- packages/activity/src/index.ts
- packages/client/src/index.ts
- packages/workflow/src/index.ts
> fix: Re-export from internal-workflow-common

- packages/common/package.json
- packages/common/src/otel.ts
- packages/interceptors-opentelemetry/src/client/index.ts
- packages/interceptors-opentelemetry/src/worker/index.ts
- packages/interceptors-opentelemetry/src/workflow/index.ts
- packages/worker/src/worker.ts
- packages/worker/src/workflow/bundler.ts
Following up on https://github.com/temporalio/sdk-typescript/pull/645#issuecomment-1158326034
> fix(worker): Disallow importing non-Workflow @temporalio packages

- packages/internal-workflow-common/src/interfaces.ts
- packages/test/src/integration-tests.ts
- packages/test/src/test-sinks.ts
- packages/test/src/test-workflows.ts
- packages/worker/src/worker.ts
- packages/workflow/src/interfaces.ts
Re: https://github.com/temporalio/samples-typescript/pull/150#discussion_r910501310
> fix: Default searchAttributes to {} and edit type

- LICENSE.md
- package.json
- packages/activity/package.json
- packages/client/package.json
- packages/common/package.json
- packages/core-bridge/package.json
- packages/create-project/LICENSE.md
- packages/create-project/package.json
- packages/interceptors-opentelemetry/package.json
- packages/internal-non-workflow-common/package.json
- packages/internal-workflow-common/package.json
- packages/meta/package.json
- packages/proto/package.json
- packages/test/package.json
- packages/worker/package.json
- packages/workflow/package.json
> docs: Update author and license company name

- package-lock.json
- packages/worker/package.json
#759
Can remove once webpack updates
> fix(worker): Update terser, fixes #759

- package-lock.json
- package.json
- packages/client/package.json
- packages/common/package.json
- packages/proto/package.json
- packages/proto/scripts/compile-proto.js
- packages/test/scripts/compile-proto.js
- packages/testing/package.json
- packages/testing/scripts/compile-proto.mjs
> chore: Upgrade to protobufjs 7

- package-lock.json
- packages/client/package.json
- packages/client/src/types.ts
- packages/client/src/workflow-client.ts
Followup to https://github.com/temporalio/sdk-typescript/pull/735#pullrequestreview-1071907277
> refactor(client)!: Remove Long

- packages/nyc-test-coverage/README.md
- packages/nyc-test-coverage/src/index.ts
- packages/nyc-test-coverage/src/interceptors.ts
@vkarpov15 this is what I meant in your PR review
> chore: Expose interceptorModule from WorkflowCoverage

- package-lock.json
- packages/test/src/helpers.ts
- packages/test/src/integration-tests.ts
- packages/test/src/test-workflows.ts
- packages/test/src/workflows/stack-tracer.ts
- packages/worker/src/worker-options.ts
- packages/worker/src/worker.ts
- packages/worker/src/workflow/vm.ts
- packages/workflow/package.json
- packages/workflow/src/index.ts
- packages/workflow/src/interfaces.ts
- packages/workflow/src/internals.ts
- packages/workflow/src/pkg.ts
- packages/workflow/src/worker-interface.ts
- packages/workflow/src/workflow.ts
Thanks @BashkirovN for coming up with the initial version.
Rewritten to avoid unnecessarily parsing stack traces, propagated version, and made tests more comprehensive.
Replaces #799
> Implement enhanced stack traces

- packages/worker/src/workflow/vm.ts
> feat: Expose additional console methods to workflow context

- packages/activity/src/index.ts
- packages/client/src/async-completion-client.ts
- packages/client/src/client.ts
- packages/client/src/index.ts
- packages/client/src/interceptors.ts
- packages/client/src/workflow-client.ts
- packages/internal-non-workflow-common/src/data-converter-helpers.ts
- packages/test/src/test-async-completion.ts
- packages/test/src/test-ephemeral-server.ts
- packages/test/src/test-testenvironment.ts
- packages/test/src/test-workflow-log-interceptor.ts
- packages/testing/src/index.ts
As discussed in the [schedules proposal](https://github.com/temporalio/proposals/blob/schedules/typescript/schedules.md#higher-level-ts-client).
> feat: Add a meta Client class

- CHANGELOG.md
Waiting for this one of course: https://github.com/temporalio/sdk-typescript/pull/906
> Add CHANGELOG entry for 1.4.2

- packages/test/src/test-workflows.ts
- packages/workflow/src/internals.ts
> fix(workflow): Don't fail workflow task if query handler not found

- packages/client/src/connection.ts
> fix(client): Fix `ConnectionOptions.connectTimeout` was not used

- packages/worker/src/debug-replayer/client.ts
Get data from responses in order to log error messages.
https://github.com/temporalio/vscode-debugger-plugin/pull/22#discussion_r1019718787
1. Closes: n/a 
2. How was this tested: n/a
3. Any docs updates needed? n/a
> Log errors for VS Code debugger

- .github/workflows/ci.yml
Depends on https://github.com/temporalio/sdk-features/pull/162
> Update to use new sdk-features CI workflow definition

- CHANGELOG.md
> chore: Update CHANGELOG for v1.5

- .github/workflows/ci.yml
> chore(ci): Use sdk-features branch 'main'

- .github/workflows/ci.yml
- CONTRIBUTING.md
Waiting on https://github.com/temporalio/sdk-features/pull/207
> Rename sdk-features to features

- packages/client/src/schedule-client.ts
- packages/client/src/schedule-types.ts
- packages/test/src/test-schedules.ts
- packages/test/src/workflows/condition-timeout-0.ts
- packages/worker/src/index.ts
> fix(client): Fix args on create/update schedules

- packages/core-bridge/Cargo.lock
Update SDK Core, in preparation for release 1.6.0
> chore(core): Update sdk-core

- CHANGELOG.md
> chore: Update CHANGELOG for v1.6.0

- packages/common/src/errors.ts
- packages/test/src/test-integration-workflows.ts
> fix: Fail workflow on WorkflowExecutionAlreadyStartedError

- package-lock.json
- packages/activity/package.json
- packages/client/package.json
- packages/common/package.json
- packages/core-bridge/Cargo.lock
- packages/core-bridge/package.json
- packages/create-project/package.json
- packages/interceptors-opentelemetry/package.json
- packages/nyc-test-coverage/package.json
- packages/nyc-test-coverage/src/globalCoverage.ts
- packages/nyc-test-coverage/src/index.ts
- packages/nyc-test-coverage/src/interceptors.ts
- packages/nyc-test-coverage/src/loader.ts
- packages/proto/package.json
- packages/test/package.json
- packages/test/src/helpers.ts
- packages/test/src/integration-tests.ts
- packages/test/src/test-local-activities.ts
- packages/test/src/test-nyc-coverage.ts
- packages/test/src/test-schedules.ts
- packages/testing/package.json
- packages/worker/package.json
- packages/workflow/package.json
- Updated SDK Core to [2e3ab26](https://github.com/temporalio/sdk-core/commit/2e3ab26fd82bdda530433af54aa6a54fce0e5caf).
- Fix schedule tests failing in Temporal CLI due to non existent search attributes
- Reduce probability of DEADLINE_EXCEEDED flakes in schedules tests
- Fix nyc-test-coverage's causing JSON parsing error (fix temporalio/samples-typescript#257)
- Fix nyc-test-coverage reporting incorrect coverage metrics in Mocha+NYC.
> Note that this DO NOT fix issues with incorrect line and incorrect coverage metrics using Jest. 
- Add 'repository' field to all published package.json files (fix #1071)
> Multiple small fixes

- CHANGELOG.md
- Updated CHANGELOG.md file to include 1.7.0 release
> chore: Add changelog entries in prep for release 1.7.0

- packages/core-bridge/Cargo.lock
- packages/core-bridge/src/conversions.rs
- packages/core-bridge/ts/index.ts
Allows SNI stuff to work properly by default when applying domain overrides in tls config
1. Closes 
> Upgrade core

- packages/core-bridge/src/runtime.rs
Apparently the comment in the code that `init_worker` will attach metrics to the client was wrong.
Fixed.
Had to put an `Arc` around the runtime, I don't think that's avoidable.
> fix: Emit metrics from core client

- packages/test/src/test-integration-workflows.ts
- Added an integration test to assert fix of #441
> chore(workflow): add test for activity retry policies

- .gitignore
- packages/client/src/build-id-types.ts
- packages/client/src/client.ts
- packages/client/src/index.ts
- packages/client/src/task-queue-client.ts
- packages/client/src/workflow-client.ts
- packages/common/src/type-helpers.ts
- packages/core-bridge/Cargo.lock
- packages/core-bridge/src/conversions.rs
- packages/core-bridge/ts/index.ts
- packages/test/src/integration-tests.ts
- packages/test/src/test-worker-versioning-unit.ts
- packages/test/src/test-worker-versioning.ts
- packages/worker/src/worker-options.ts
- tsconfig.prune.json
Support for the new Worker Versioning feature
> Worker versioning

- packages/client/src/task-queue-client.ts
- packages/common/src/activity-options.ts
- packages/common/src/index.ts
- packages/common/src/versioning-intent.ts
- packages/test/src/test-replay.ts
- packages/test/src/test-worker-versioning-unit.ts
- packages/test/src/test-workflows.ts
- packages/worker/src/worker.ts
- packages/workflow/src/interfaces.ts
- packages/workflow/src/workflow.ts
https://github.com/temporalio/sdk-typescript/pull/1146 accidentally left out `VersioningIntent` for commands. This adds that.
> Add versioning intent to commands

- CHANGELOG.md
- Add changelog entries for release 1.8.1
> chore: Prepare CHANGELOG.md for release 1.8.1

- packages/worker/src/index.ts
> fix(worker): Export WorkerStatus interface

- CHANGELOG.md
- Add changelog entries for release 1.8.2
> Prepare CHANGELOG.md for release 1.8.2

- CHANGELOG.md
- packages/worker/src/index.ts
- packages/worker/src/replay.ts
- packages/worker/src/worker-options.ts
- packages/worker/src/worker.ts
- packages/worker/src/workflow/bundler.ts
- Fix multiple typos on "workflow"
> fix: Fix multiple typos on "workflow"

- packages/worker/src/runtime.ts
- Do not use RxJS to poll log entries from core (fix #1224)
- This change was forked out of #1225, as more work needs to be done on exporting log metadata out of Core.
> fix(worker): Avoid rxjs error while flushing logs on worker shutdown

- CHANGELOG.md
- Update CHANGELOG.md in prep for 1.8.5
> chore: Update CHANGELOG in prep for 1.8.5

- packages/worker/src/runtime.ts
This hopefully would fix the memory leak we've seen in the latest nightly run.
> fix(worker): Remove rx subject in Runtime

- CHANGELOG.md
- Update CHANGELOG in preparation for 1.8.6
> chore: Update CHANGELOG in preparation for 1.8.6

- packages/core-bridge/Cargo.lock
- packages/core-bridge/Cargo.toml
- packages/core-bridge/src/helpers.rs
- packages/core-bridge/src/runtime.rs
- packages/core-bridge/ts/index.ts
- packages/test/src/test-runtime.ts
- packages/worker/src/runtime.ts
- Retain meta on log entries forwarded from core (fix #1195)
> feat(worker): Retain meta on log entries forwarded from core

- packages/common/src/activity-options.ts
- packages/common/src/versioning-intent.ts
- packages/workflow/src/interfaces.ts
Wrapped comment based on prettierrc's printwidth: 120
> docs: Specify default `VersioningIntent`

- packages/worker/src/worker.ts
This PR refactors an important function that has high complexity and is also long (250 lines), and contains several important sub-components that would benefit from being given their own names and abstracted out as separate functions. (Although I wasn't familiar with rxjs, I'm not critizing its use here -- I believe we are getting a lot of leverage out of it, and that it is aiding rather than hindering comprehension.)
The starting point was
```typescript
workflowOperator(): OperatorFunction<WorkflowActivation, Uint8Array>
```
Its job is to create an rxjs operator to perform the worker's processing of all activations (from all workflows).
We break `workflowOperator` up as follows:
_(Choosing good names is important if this change is to be useful. I'd love to hear any alternative …
> Refactor rxjs activation processing

- packages/core-bridge/Cargo.lock
- packages/core-bridge/Cargo.toml
- packages/core-bridge/src/conversions.rs
- packages/core-bridge/src/runtime.rs
- packages/test/src/test-prometheus.ts
Prometheus initialization would explode because it needs tokio to exist, but was being initialized before tokio was.
> Fix metric meter initialization

- packages/client/src/workflow-options.ts
More info here:
https://github.com/temporalio/sdk-typescript/pull/1277#discussion_r1379012215
> docs: Explain the purpose of `updateId`

- packages/client/src/connection.ts
- packages/core-bridge/Cargo.lock
- packages/core-bridge/src/conversions.rs
- packages/core-bridge/src/lib.rs
- packages/core-bridge/src/runtime.rs
- packages/core-bridge/ts/index.ts
- packages/test/src/test-client-connection.ts
- packages/test/src/test-native-connection-headers.ts
- packages/testing/src/connection.ts
- packages/worker/src/connection-options.ts
- packages/worker/src/connection.ts
- packages/worker/src/runtime.ts
Add api-key helper methods for both kinds of clients
Parity
1. Closes https://github.com/temporalio/sdk-typescript/issues/1367
Upgraded tests
> Api Key Support

- CONTRIBUTING.md
- lerna.json
- package-lock.json
- package.json
- packages/core-bridge/Cargo.lock
- packages/create-project/package.json
- packages/test/package.json
- Update various dependencies in preparation for 1.10.0 release.
- Among other things, updated to Lerna 7 and native NPM workspaces.
> chore: Update to lerna 7 and update other deps

- .github/workflows/ci.yml
- Remove references to the custom branch in features testing, since that test has now been merged to main.
> chore: Remove reference to custom features branch

- packages/common/src/converter/failure-converter.ts
- packages/common/src/errors.ts
- packages/common/src/failure.ts
- packages/common/src/time-base.ts
- packages/common/src/time.ts
- packages/core-bridge/Cargo.lock
- packages/core-bridge/src/worker.rs
- packages/test/src/test-integration-workflows.ts
- packages/test/src/test-worker-activities.ts
- packages/test/src/workflows/child-workflow-start-fail.ts
Expose the new next retry delay field for activity failures
Parity
1. Closes https://github.com/temporalio/sdk-typescript/issues/1349
Added test verifying property is sent to Core, where functionality is already tested
> Expose next retry delay

- packages/workflow/src/worker-interface.ts
Literally just one typo
Seems like a typo.
1. Closes 
> 1 single typo fix

- package-lock.json
- Updating dependencies on the `releases/1.10.x` branch
> chore: Update dependencies in prep for v1.10.2

- .github/workflows/ci.yml
- .github/workflows/omes.yml
Adding omes worker image build to all SDKs
> Build omes worker image

- packages/worker/src/workflow/bundler.ts
Fix broken link to https://typescript.temporal.io/api/interfaces/worker.workeroptions/#bundleroptions, it returns a `404: NOT_FOUND`
1. Closes 
> fix link to apidoc workflowbundleoption

- package-lock.json
- packages/docs/package-lock.json
- packages/docs/src/theme/DocBreadcrumbs/index.js
- `npm audit fix` in root and docs packages
> chore: Upgrade multiple vulnerable deps

- packages/core-bridge/ts/index.ts
Clarifying the expected format and the semantics.
Context: https://temporalio.slack.com/archives/C02MTL0GEKH/p1726577174636549
> Document OtelCollectorExporter.otel property

- packages/common/src/activity-options.ts
> activity-options: docs

- .eslintrc
- package-lock.json
- package.json
- packages/cloud/src/cloud-operations-client.ts
- packages/common/src/converter/payload-converter.ts
- packages/common/src/internal-non-workflow/data-converter-helpers.ts
- packages/common/src/type-helpers.ts
- packages/create-project/src/helpers/fetch-samples.ts
- packages/create-project/src/helpers/git.ts
- packages/create-project/src/helpers/is-online.ts
- packages/create-project/src/helpers/samples.ts
- packages/test/src/integration-tests-old.ts
- packages/test/src/load/setup.ts
- packages/test/src/payload-converters/payload-converter-no-export.ts
- packages/test/src/test-client-connection.ts
- packages/test/src/test-integration-workflows.ts
- packages/test/src/test-interface-type-safety.ts
- packages/test/src/test-iterators-utils.ts
- packages/test/src/test-sinks.ts
- packages/test/src/workflows/stack-tracer.ts
- packages/worker/src/runtime.ts
- packages/worker/src/worker.ts
- packages/worker/src/workflow/threaded-vm.ts
- packages/workflow/src/interceptors.ts
- packages/workflow/src/worker-interface.ts
- Upgraded project to TypeScript 5.6.
- Prep change for #1534.
> chore: Upgrade to TypeScript 5.6

- packages/client/src/async-completion-client.ts
- packages/core-bridge/Cargo.lock
- packages/core-bridge/src/runtime.rs
> chore: Update Core to latest

- .github/workflows/ci.yml
- Fix missing env variables while configuring cert directory in CI.
> chore: Fix error in CI due to missing env variables

- packages/worker/src/worker.ts
This PR fixes a typo on the log message
> fix(worker): typo

- packages/test/src/test-interface-type-safety.ts
- packages/workflow/src/interfaces.ts
Fixes https://github.com/temporalio/sdk-typescript/issues/1628
> fix(workflow): Do not appear to support conflict policy for child workflows

- packages/core-bridge/src/conversions.rs
Upgraded sdk-core to 93471ac
Need updates to our proto definitions for Task Queue Priority Annotations
1. Closes 
> chore(core): Upgrade Core

- package-lock.json
- packages/docs/docusaurus.config.js
- packages/docs/package-lock.json
- packages/docs/package.json
- Update dependencies on the docs package
> chore: Update vulnerable dependencies on docs pacakge
